var powerData = [["He aims a gun _____ a target.", "at" ],
["I attached blank cards ____ the board.","on"],
["A lady invites you ____ the party.","to"],
["The breadth of the road is limited ____ 10 meter.","to"],
["He loads the car ____ the luggage.","with"],
["He pours water ____ the cup.","into"],
["People praised me ____ my job.","for"],
["The family divides (themselves) ____ two groups.","into"],
["Cows provide milk ____ us.","for"],
["He injects medicine ____ the vein.","into"],
["They join on block ____ another.","to"],
["An accident happens ____ him.","to"],
["She shoots ____ him.\nA man was shot ____ the leg.","at, in"],
["He sacrificed himself ____ us.","for"],
["He fills a cup ____ water.","with"],
["We export goods ____ foreign countries.","to"],
["She gets all the data ____ the roll.","from"],
["He lies ____ the lawn.","on"],
["He combines each part ____ one.","into"],
["She drinks water ____ a bottle.","out of"],
["I add red balls ____ the black balls.","to"],
["She blows seeds ____ a flower.","off"],
["Girls are burying their friend ____ (two buckets of) sand.","in"],
["She chooses her house ____ the two.","between(among)"],
["A red apple belongs ____ a row of apples.","to"],
["He sends a letter ____ her.","to"],
["A lady is going to vote ____ the candidate of her favorite party.","for"],
["The parents kiss their daughter ____ the cheeks.","on"],
["A boy learns something ____ his father.","from"],
["A father lifts his child ____ the air","up in"],
["He shakes hands ____ her.","with"],
["She points (a finger) ____ an empty card.","at"],
["She (intends to) reduces her weight ____ 50kg.","to"],
["The picture reminds her ____ her husband.","of"],
["She received flowers ____ her student.","from"],
["She sits ____ the street.","on"],
["She announces her marriage ____ her friends.","to"],
["The balls have returned ____ the hole ____ us.","from, to"],
["She collects money ____ the floor by doing what she likes.","from"],
["She depends ____ her mother.","on"],
["A policeman directs a person ____ the museum.","to"],
["A golden fish escapes ____ the water.","out of"],
["Please excuse me ____ my fault.","for"],
["He expresses his love ____ us.","to"],
["He guards the building ____ the enemy","against"],
["He puts a ball ____ the grass.","on"],
["How did she react ____ the idea?","to"],
["They cure him ____ the toothache.","of"],
["A car is damaged ____ a car accident.","by"],
["He defends himself ____ the enemy.","from"],
["She disputes ____ him ____ the plan.","with, about"],
["The map guides them(____ the desert) ____ their destination.","through, to"],
["The dictionary defines the word ____ \"Femailes or males considered as a group.\"","as"],
["The event is postponed ____ the following day.","until"],
["He is pushing his car ____ the garage for repair.","toward"],
["He turns the doorknob ____.","around"],
["She is changing the bad cover ____ the new one.","with"],
["The ticket admits her ____ the best show.","to"],
["The police arrested him ____ murder.","for"],
["She has arrived ____ the station.","at"],
["I borrow a USB drive ____ my friend.","from"],
["She will punish him ____ the failure.","for"],
["A man breathes new life ____ his old friend.","into"],
["The restaurant charges this ____ my account.","to"],
["Our team was defeated ____ the weakest team ____ the area.","by, in"],
["She fixes a bow tie ____ his neck.","on"],
["They go (____) ____ the top of the mountain.","up, to"],
["She has purchased new arrivals ____ 100 dollars.","for"],
["She connects herself ____ her sister.","to"],
["She takes a key ____ her mother.","from"],
["She informs them ____ the test results.","of"],
["The ship transports goods ____ many countries.","to"],
["She knows ____ the answer.","about"],
["I will give a present ____ you.","to"],
["He separated pieces ____ the puzzle.","from"],
["They covered their eyes ____ both hands.","with"],
["He criticizes her ____ her behavior.","for"],
["She said something ____ me.","to"],
["She laughs ____ the gift.","at"],
["He leaves his office ____ the bus station.","for"],
["She notes her thought (____) ____ her notepad at the table.","down, on"],
["I will tie him ____ the pole.","to"],
["Fireworks burst ____ the night sky.","into"],
["Their attempt has resulted ____ success.","in"],
["The dollar is decreasing ____ value.","in"],
["He will recover himself ____ illness.","from"],
["He is removing the front wheel ____ the car.","from"],
["He was shocked ____ the news.","at"],
["She compares one ____ another.","with"],
["They have been waiting a lot ____ the interview.","for"],
["We are developing natural resources ____ valuable things.","into"],
["A child brings the phone ____ his mother.","to"],
["The seed is growing (____) ____ a tree.","up, into"],
["I share the USB drive ____ her.","with"],
["He is severely injured ____ a blow.","by"],
["He invests his money ____ stocks.","in"],
["He interferes ____ the opposing player's spike.","with"],
["He agrees ____ him ____ his proposal.","with, on"],
["She appeals ____ people ____ her election.","to, for"],
["He tries to apologize ____ her ____ (the help of) a flower.","to, with"],
]
//["",""],




