var data = [
    ["drive", "drove", "driven", "driving", "운전하다", "drives"],
    ["ride", "rode", "ridden", "riding", "(탈것에)타다", "rides"],
    ["write", "wrote", "written", "writing", "(글씨를)쓰다", "writes"],
    ["break", "broke", "broken", "breaking", "부수다", "breaks"],
    ["choose", "chose", "chosen", "choosing", "선택하다", "chooses"],
    ["forget", "forgot", "forgotten", "forgetting", "잊다", "forgets"],
    ["freeze", "froze", "frozen", "freezing", "얼다", "freezes"],
    ["speak", "spoke", "spken", "speaking", "말하다, 연설하다", "speaks"],
    ["steal", "stole", "stolen", "stealing", "훔치다", "steals"],
    ["begin", "began", "begun", "beginning", "시작하다", "begins"],
    ["drink", "drank", "drunk", "drinking", "마시다", "drinks"],
    ["run", "ran", "run", "running", "달리다", "runs"],
    ["shrink", "shrank", "shrunk", "shrinking", "줄어들다", "shrinks"],
    ["sing", "sang", "sung", "singing", "노래하다", "sings"],
    ["spring", "sprang", "sprung", "springing", "튀어오르다", "springs"],
    ["swim", "swam", "swum", "swimming", "수영하다", "swims"],
    ["mistake", "mistook", "mistaken", "mistaking", "실수하다", "mistakes"],
    ["shake", "shook", "shaken", "shaking", "흔들다", "shakes"],
    ["take", "took", "taken", "taking", "잡다", "takes"],
    ["blow", "blew", "blown", "blowing", "불다", "blows"],
    ["fly", "flew", "flown", "flying", "날다", "flies"],
    ["grow", "grew", "grown", "growing", "자라다", "grows"],
    ["know", "knew", "known", "knowing", "알다", "knows"],
    ["throw", "threw", "thrown", "throwing", "던지다", "throws"],
    ["withdraw", "withdrew", "withdrawn", "withdrawing", "(돈을)인출하다 철회하다", "withdraws"],
]
//["", "", "", "", "", ""],