var imageArticlesData = [["A father and his child go down a water slide."],
["A man puts oil on a bicycle chain."],
["A woman is in a raincoat and she rides her bike."],
["A man writes his name on a waiting list for the blood donation at the RedCross office in Tokyo."],
["A rainbow appears over a lighthouse."],
["A volunteer collects money from a woman in the market."],
["A man takes a break on his tricycle outside a store."],
["The sun shines behind the price board at a gas station."],
["A bullfighter stands behind the wall with the shadow of a bull."],
["A bullfighter leans and touches the bull with long spears in the back."],
["A bullfighter falls to the ground after the bull's attack on the horse."],
["A fighting bull goes through the legs of a bullfighter."],
["Several men run and look back over their shoulders at bulls."],
["A bull hits a man and (it) sends him to the fence."],
["A man lies on the ground when bulls pass him."],
["A bullfighter is knocked down by a bull."],
["A man gives a thumbs up to people and he is carried on a stretcher by the rescue men to the hospital."],
["A nurse sits outside a room at a houspital."],
["A man pushes his cart to the market when he walks past a large shopping bag."],
["A man raises belts (up) into the air when he sells his goods (to the customers) at the market."],
["Girls buy items from a vendor in the market."],
["A woman puts rings around her wrist."],
["A shopkeeper browses a dictionary and she waits for customers."],
["A campaign girl pours water on the movie camera."],
["He looks through binoculars."],
["A welcoming banner hangs on a bridge over the cars in the street."],
["Fireworks explode from the beach into the sky as a lot of people watch them."],
["He is answering questions from reporters after a press conference."],
["A singer puts his handprints into a cement next the frame."],
["A man looks into a car."],
["People use butterfly nets for apples at the Cheonggyecheon, a restored stream."],
["A man jumps into the arms of the crowd."],
["Sunflowers must be dried on a field."],
["Visitors sit on the steps of the museum and rest in the shade after sightseeing."],
["A man has fallen asleep in his chair outside the office."],
["A woman protects herself with her handbag from the sun at the bus station."],
["A young woman can cool herself in the water of a fountain."],
["Local people sit under an umbrella during a heavy rainfall."],
["Students hold umbrellas in the rain and they run across the road."],
["They struggle to hold their umbrella in the strong wind."],
["A tower is high above the town."],
["A car makes its way through flood water after continuous heavy rainfall."],
["An old woman sits in the chair with floodwater in the house after the typhoon."],
["A father carries his daughter on his back in a flooded area amid a tropical storm."],
["You can take a view from the 63 Building in Yeouido and it shows a clean blue sky over downtown Seoul after typhoon."],
["An animal is licking snow off its nose an the zoo in Hamburg, Germany."],
["Foreign expats and Koreans make kimchi with 2,000 heads of cabbages at Namsangol Hanok Village in Seoul. The Kimchi will be delivered to 500 needy households."],
["People put masks on their mouths for protection."],
["She stands amid yellow leaves."],
["A surfer tries to ride some of the large waves."],
["Two men lower a young girl down into the water for the religious service in the river."],
["School students are taking their temperatures together in class."],
["People queue under the rain outside the Apple store in Beijing before the ipad's sale in China."],
["People are in winter jacket and walk on a street in sinchon, a college district in Seoul, Friday. The mercury dropped below zero"],
["An applicant is tested for back strength at a physical examination as others wait for their turn."],
["Women`s university students apply for ROTC and perform push-ups during the physical fitness test at the ground."],
["A soldier stands on duty at the entrance to the barracks."],
["A fighter is soaring into the clear blue skies and it makes a big impression to people."],
["A girl plays next to a polluted stream on a roadside."],
["White smoke comes from a factory before the moon."],
["A woman takes oxygen from a can."],
["An oxygen can is sold as a refreshment for stressed people."],
["Environmental activists paint huge 'smoking Kills' on the face of a coal power station in the city"],
["A Chinese dustman collects floating rubbish from the river in a county."],
["A factory worker puts(pushes) waste cardboard boxes into a machine at a recycling factory."],
["A boy pumps clean water from a village well into his container."],
["A factory worker pulls waste cardboard boxes out of a machine at a recycling factory."],
["Port workers move old trucks into a cargo boat at the port of Beijing, China."],
["A woman waves from the inside of a chinese made electric car at the exhibition in Beijing."],
["A farmer sprays pesticide over rice."],
["A man rides a bike along the beach as the sun sets beyond the mountain."],
["A farmer dries hot peppers on huge mats in the farm vilage on a sunny afternoon as summer gives way to Fall."],
["A seaweed farmer gathers seaweed from the net at a beach."],
["A woman controls her boat along the river under the bridge in the water town, 90km from Shanghai."],
["Elderly men and women participate in a harmonica class at a community center."],
["A plane can be observed by a couple under a sun umbrella."],
["Customers enjoy coffee with toilets and bath products in a cafe at the department store, central Seoul."],
["A man is riding his bicycle through a large puddle of wasted water on the street during the repair of a water pipe in Beijing."],
["People stand in line next to plastic containers (before a gas tank) outside a fuel station as they wait for gasoline for cooking."],
["Gasoline sellers pour gasoline into bottles for sale.\nThey fill bottles with gasoline."],
["Protesters chained themselves across the motorway against a test of a new motorway."],
["A protester throws a tomato at a poster in front of the building."],
["A presidential candidate waves to her supporters around her van during a rally on a street near the major city."],
["A doctor puts his ballot into the ballot box during the vote (before his friend)."],
["A tourist holds a child up during his sightseeing trip at the station."],
["A catcher waits for the ball as Choo Sin-Soo slides to the home plate in the third inning."],
["Workers collect honey from boxes which contain thousands of bees."],
["A man rides a tricycle that is loaded with empty bottles which will be used again."],
["A woman walks through a housing complex which was torn down for a new subway station."],
["A woman walks across the blue paths which represent the ocean."],
["People fish apples with nets at the Cheonggyecheon which is a restored stream that runs through downtown Seoul. The event was held for the promotion of apple-harvesting season."],
["A train runs on the railway which runs across the frozen land."],
["A man takes a rest amid leaves which have fallen off a tree."],
["People sunbath on the beach in front of a bunker which was left behind the Japanese soldiers."],
["A man is reading the newspaper which reports on the new plan that will finish conflicts."],
["He looks (at the engine) under the hood of a new car which is given by American Red Cross."],
["American Red Cross gives a new car whose hood is over a man who looks at the engine."],
["Police conduct their investigation on the scene where crime occurred."],
["A farmer who is spreading seeds over the field makes his way through the field."],
["A boy who carries two balloons walks past a display of juice boxes in a supermarket."],
["A man who is with pens and stationery walks past a wall with election campaign posters in the capital city."],
["A woman who is passing a stone that marks the start of the long railway walks on the railway."],
["A woman who is paralyzed from the chest down speaks at a news conference."],
["School students who are diagnosed with high temperature are put in a holding room."],
["A scientist picks a small part of a bone for a DNA analysis."],
["Officials bring three suspects to the court."],
["A couple took their child for a stroll in Beijing last weekend when they could relax."],
["A woman walks past a car that hangs on an advertising board which Hyundai made."],
["A man looks into a car which is displayed on the floor."],
["A woman looks over cars which will be sold in an upcoming auction.\nA woman looks over cars she hope to buy in an upcoming auction."],
["The car whose body is red is looked by a lady who has lots of money whose owner was her father that earned money from working hard."],
["She prepares the order (which) a customer asked."],
["The actor who played a leading role in the new film waves to reporters."],
["A dancer jumps up into the air as tourists watch his performance."],
["People walk on the bridge over the river when the sun sets."],
["A man stands in front of a copper dragon that was designed for the China Days."],
["Dog handlers pose with their animals for photographers."],
["A hare runs in a field which is covered with snow near the village where my grandfather lives."],
["Lion cubs Shalmon and Salam, whose names mean Peach in Hebrew and Arabic respectively, are seen as they are taken from their cage."],
["Men gather around a horse that died of exhaustion near the finish line of a long horse race."],
["A chimpanzee enjoys a piece of ice candy which is composed of frozen fruit."],
["An oranutan eats a slice of water melon during the hot summer weather at South Korea's largest amusement park Everland, on Yongin-si in Gyeonggi Province, South Korea."],
["A squirrel monkey dangles at a cord as he is sucking an ice block with fruit pieces in a zoo."],
["A worker who pushes his cart to the workplace goes past houses that are still under construction."],
["A woman tha looks toward the camera stands on the debris of a former neighbor's house."],
["A man rests by(against) a garbage can near the moument which is undergoing repairs."],
["A girl brings a tray of food to her table where her friends are waiting during the lunch rush at KFC."],
["Citizens who are dressed in comic outfits and wigs enjoy an event that is held in front of Hongik University which is famous for youthful art in northern Seoul Thursday."],
["Protestors who demand reforms throw stones at policemen during the protest rally."],
["A policeman who is bleeding covers his face (with his handkerchief) during the protest in the capital."],
["Farmers have destroyed their cherry production because they can't <export|import> their goods (<to|from> foregin countries)."],
["Police officers talk with passengers (about their flight) at the aiport as workers are on a strike to (that they may) demand a raise up to $100."],
["A passenger looks out just as two hundred workers who are on a strike block the airport runways and stop the air traffic."],
["Thousands of passengers stand in the departure hall while they wait for their flight on the second day of the strike."],
["Social workers who are from Nowon District Office conduct a survey of senior citizens over 65 years old who live alone at Junggye-dong, northern Seoul, Monday.\n\nThe survey that is conducted on some 210,000 elderly people who live alone will be used as basic data, (in order) that Nowon District Office may help them."],
["A worker who helps the people in trouble unloads a crate of eggs from the truct at the nursing home."],
["A volunteer carries a bag of rice with his friends in the donation event of rice to poor people in Bupyeong-dong, Incheon.\n\nThe donation took place ahead of the Chuseok holiday which falls on Sept. 22."],
["\"School sheriffs\" who have been trained to protect students around schools make their debut."],
["Volunteers prepare viola flowers for sale at a farm as spring has finally arrived."],
]
//[""],
