var imageArticlesData = [["A father and his child go down a water slide."],
["A man puts oil on a bicycle chain."],
["A woman is in a raincoat and she rides her bike."],
["A man writes his name on a waiting list for the blood donation at the RedCross office in Tokyo."],
["A rainbow appears over a lighthouse."],
["A volunteer collects money from a woman in the market."],
["A man takes a break on his tricycle outside a store."],
["The sun shines behind the price board at a gas station."],
["A bullfighter stands behind the wall with the shadow of a bull."],
["A bullfighter leans and touches the bull with long spears in the back."],
["A bullfighter falls to the ground after the bull's attack on the horse."],
["A fighting bull goes through the legs of a bullfighter."],
["Several men run and look back over their shoulders at bulls."],
["A bull hits a man and (it) sends him to the fence."],
["A man lies on the ground when bulls pass him."],
["A bullfighter is knocked down by a bull."],
["A man gives a thumbs up to people and he is carried on a stretcher by the rescue men to the hospital."],
["A nurse sits outside a room at a houspital."],
["A man pushes his cart to the market when he walks past a large shopping bag."],
["A man raises belts (up) into the air when he sells his goods (to the customers) at the market."],
["Girls buy items from a vendor in the market."],
["A woman puts rings around her wrist."],
["A shopkeeper browses a dictionary and she waits for customers."],
["A campaign girl pours water on the movie camera."],
["He looks through binoculars."],
["A welcoming banner hangs on a bridge over the cars in the street."],
["Fireworks explode from the beach into the sky as a lot of people watch them."],
["He is answering questions from reporters after a press conference."],
["A singer puts his handprints into a cement next the frame."],
["A man looks into a car."],
["People use butterfly nets for apples at the Cheonggyecheon, a restored stream."],
["A man jumps into the arms of the crowd."],
["Sunflowers must be dried on a field."],
["Visitors sit on the steps of the museum and rest in the shade after sightseeing."],
["A man has fallen asleep in his chair outside the office."],
["A woman protects herself with her handbag from the sun at the bus station."],
["A young woman can cool herself in the water of a fountain."],
["Local people sit under an umbrella during a heavy rainfall."],
["Students hold umbrellas in the rain and they run across the road."],
["They struggle to hold their umbrella in the strong wind."],
["A tower is high above the town."],
["A car makes its way through flood water after continuous heavy rainfall."],
["An old woman sits in the chair with floodwater in the house after the typhoon."],
["A father carries his daughter on his back in a flooded area amid a tropical storm."],
["You can take a view from the 63 Building in Yeouido and it shows a clean blue sky over downtown Seoul after typhoon."],
["An animal is licking snow off its nose an the zoo in Hamburg, Germany."],
["Foreign expats and Koreans make kimchi with 2,000 heads of cabbages at Namsangol Hanok Village in Seoul. The Kimchi will be delivered to 500 needy households."],
["People put masks on their mouths for protection."],
["She stands amid yellow leaves."],
["A surfer tries to ride some of the large waves."],
["Two men lower a young girl down into the water for the religious service in the river."],
["School students are taking their temperatures together in class."],
["People queue under the rain outside the Apple store in Beijing before the ipad's sale in China."],
["People are in winter jacket and walk on a street in sinchon, a college district in Seoul, Friday. The mercury dropped below zero"],
["An applicant is tested for back strength at a physical examination as others wait for their turn."],
["Women`s university students apply for ROTC and perform push-ups during the physical fitness test at the ground."],
["A soldier stands on duty at the entrance to the barracks."],
["A fighter is soaring into the clear blue skies and it makes a big impression to people."],
["A girl plays next to a polluted stream on a roadside."],
["White smoke comes from a factory before the moon."],
["A woman takes oxygen from a can."],
["An oxygen can is sold as a refreshment for stressed people."],
["Environmental activists paint huge 'smoking Kills' on the face of a coal power station in the city"],
["A Chinese dustman collects floating rubbish from the river in a county."],
["A factory worker puts(pushes) waste cardboard boxes into a machine at a recycling factory."],
["A boy pumps clean water from a village well into his container."],
["A factory worker pulls waste cardboard boxes out of a machine at a recycling factory."],
["Port workers move old trucks into a cargo boat at the port of Beijing, China."],
["A woman waves from the inside of a chinese made electric car at the exhibition in Beijing."],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
[""],
]
//[""],
