var questionData = [[	"오렌지 주스는 어디 있죠?"	,	"Where is orange juice?"	]	,
                 [	"올림픽 게임은 얼마나 자주 개최되나요?"	,	"How often is the olympic game held?"	]	,
                 [	"왜 더 머물지 않으시나요?"	,	"Why don't you stay longer?"	]	,
                 [	"언제 거기 갔었지?"	,	"When did you go there?"	]	,
                 [	"걸혼식이 몇시인가요?"	,	"What time is the wedding ceremony?"	]	,
                 [	"왜 우리는 영어를 꼭 공부해야만 하나요?"	,	"Why must we study English?"	]	,
                 [	"우리 어디서 내려야 하나요?"	,	"Where should we get off?"	]	,
                 [	"우리 어디서 먹을 건가요?"	,	"Where will we eat?"	]	,
                 [	"우리가 얼마나 멀리 걸어온 겁니까?"	,	"How far have we walked?"	]	,
                 [	"이 가방은 누구의 것입니까?"	,	"Whose is this bag?"	]	,
                 [	"당신은 신문에서 어느 기사를 읽었나요?"	,	"Which article did you read in the paper?"	]	,
                 [	"이 서류 어떻게 찾았어?"	,	"How did you find this document?"	]	,
                 [	"누가 이 영화를 감독했나요?"	,	"Who directed this movie?"	]	,
                 [	"저 건물들은 왜 무너졌니?"	,	"Why were those buildings destroyed?"	]	,
                 [	"누가 이 우산을 가져왔나요?"	,	"Who brought this umbrella?"	]	,
                 [	"그 게임은 얼마나 빨리 끝날까요?"	,	"How soon will the game end?"	]	,
                 [	"그녀가 너한테 뭐라고 말한 거야?"	,	"What did she tell you?"	]	,
                 [	"그가 그것을 위해 얼마나 많이 지불했나요?"	,	"How much did he pay for it?"	]	,
                 [	"그것은 언제 시작해야 하나요?"	,	"When should it start?"	]	,
                 [	"누가 휴식을 취하길 원하나요?"	,	"Who wants to take a break?"	]	,
                 [	"그녀는 그녀의 달갈들을 어떻게 원하나요?"	,	"How does she want her eggs?"	]	,
                 [	"그녀의 집은 어딨니?"	,	"Where is her house?"	]	,
                 [	"왜 오늘은 당신에게 좋은 날이었나요?"	,	"Why was today a good day for you?"	]	,
                 [	"그는 어디에서 근무하나요?"	,	"Where does he work?"	]	,
                 [	"그는 언제 결혼할 건가요?"	,	"When will he marry?"	]	,
                 [	"그는 왜 새 옷을 필요로 하나요?"	,	"Why does he need new clothes?"	]	,
                 [	"누가 내 봉투를 던져 버렸나요?"	,	"Who threw away my envelope?"	]	,
                 [	"그의 아들은 아침에 언제 일어나나요?"	,	"When does his son get up in the morning?"	]	,
                 [	"왜 그 남자가 그 여자에게 축하 했나요?"	,	"Why did the man congratulate the woman?"	]	,
                 [	"너 어떻게 지내왔니?"	,	"How have you been?"	]	,
                 [	"이 옷은 어떻나요?"	,	"How is this dress?"	]	,
                 [	"기차가 언제부터 저기에 서 있었어요?"	,	"Since when has the train stood there?"	]	,
                 [	"누가 그녀를 회사에 태워다 줬나요?"	,	"Who drove her to her company?"	]	,
                 [	"당신은 내일 뭘 할건가요?"	,	"What will you do tomorrow?"	]	,
                 [	"당신은 먹고 살기 위해서 뭘 하세요?"	,	"What do you do for a living?"	]	,
                 [	"당신은 얼마나 자주 커피를 마시나요?"	,	"How often do you drink coffee?"	]	,
                 [	"당신은 무슨 비행기를 탈 건가요?"	,	"What flight will you take?"	]	,
                 [	"언제 날씨가 개일까요?"	,	"When will the weather(it) be fine?"	]	,
                 [	"당신은 어제 아침 얼마나 늦었나요?"	,	"How late were you yesterday morning?"	]	,
                 [	"수업은 얼마 동안 진행 되나요?"	,	"How long does the class last?"	]	,
                 [	"누가 그들을 행복하게 할 수 있나요?"	,	"Who can make them happy?"	]	,
                 [	"당신은 왜 내일 여기에 올 수 없나요?"	,	"Why can't you come here tomorrow?"	]	,
                 [	"누가 내 차의 유리창을 깼어?"	,	"Who broke the window of my car?"	]	,
                 [	"당신은 왜 쇼핑을 가지 않았나요?"	,	"Why didn't you go shopping?"	]	,
                 [	"당신은 얼마나 큰가요?"	,	"How tall are you?"	]	,
                 [	"당신의 생일은 언제인가요?"	,	"When is your birthday?"	]	,
                 [	"James는 어디에 기타를 놔두었나요?"	,	"Where did James leave his guitar?"	]	,
                 [	"사무실 안에서 누가 일하고 있죠?"	,	"Who is working in the office?"	]	,
                 [	"당신은 뭘 찾고 있어요?"	,	"What are you looking for?"	]	,
                 [	"왜 영어가 필수적인가요?"	,	"Why is English essential?"	]	,
                 [	"당신은 어느 정도 영어를 말하고 싶나요?"	,	"How well do you want to speak English?"	]	,
                 [	"누가 그를 미국에 초청했나요?"	,	"Who invited him to America?"	]	,
                 [	"다음 버스가 언제 도착하죠?"	,	"When will the next bus arrive?"	]	,
                 [	"당신 아버지는 왜 저렇게 화가 나셨나요?"	,	"Why is your father so angry?"	]	,
                 [	"누가 지금 사무실에서 근무하나요?"	,	"Who works at the office now?"	]	,
                 [	"어느 것이 선택되었나요?"	,	"Which was chosen?"	]	,
                 [	"어느 호텔에서 묵을 건가요?"	,	"Which hotel will you stay at?"	]	,
                 [	"어디서 잃어버렸나요?"	,	"Where did you lose it?"	]	,
                 [	"어떤 상점이 TV를 싸게 파나요?"	,	"Which store sells TV sets cheap?"	]	,
                 [	"어제 누가 그녀의 아이를 집에 데려다 주었나요?"	,	"Who took her child home yesterday?"	]	,
                 [	"언제 우리가 다시 모일까요?"	,	"When will we gather together?"	]	,
                 [	"언제부터 당신은 그를 알아 왔습니까?"	,	"Since when have you known him?"	]	,
                 [	"지구는 어디서 빛을 받나요?"	,	"Where does the earth get its light?"	]	,
                 [	"누가 공항에서 그를 맞이할까요?"	,	"Who will meet him at the airport?"	]	,
                 [	"그는 무엇에 대해 생각 하고 있는 중이니?"	,	"What is he thinking about?"	]	,
                 [	"Brian은 누구하고 점심을 먹나요?"	,	"Who does Brian have lunch with?"	]	,
                 [	"Jack은 중학교 이후에 어디서 살았니?"	,	"Where has Jack lived after middle school?"	]	,
                 [	"당신의 아이들은 언제 방학을 할 건가요?"	,	"When will your children take their vacation?"	]	,
                 [	"Paul은 누구를 기다리고 있는 중인가요?"	,	"Who is Paul waiting for?"	]	,
                 [	"그녀는 쭉 어떤 종류의 음악을 좋아해 오고 있나요?"	,	"What kind of music has she liked?"	]	,
                 [	"Timmy는 여자친구랑 왜 해어졌어?"	,	"Why did Timmy break up wih his girlfriend?"	]	,
                 [	"이 많은 강아지들 중에서 어떤 것이 그의 제일 좋아하는 강아지야?"	,	"Which is his favorite puppy among these many puppies?"	]	,
                 [	"이제 우리는 반드시 어디로 가야만 할까? (have to 사용)"	,	"Where do we have to go now?"	]	,
                 [	"60세 생신을 위해 너의 아버지께 우리가 무엇을 선물해야 할까?"	,	"What should we present to your father for his 60th birthday anniversary?"	]	,
                 [	"그들은 여기 오기 전에 어디서 공부를 했었었나요?"	,	"Where had they studied before they came?"	]	,
                 [	"그들의 부모님은 언제 미국으로 돌아가실 건가요?"	,	"When will their parents come back to America?"	]	,
                 [	"그들의 부모님은 언제부터 그들이 좋은 시간을 가지도록 허락해 왔나요?"	,	"Since when have their parents allowed them to have good times?"	]	,
                 [	"네가 말하지 않은 것들을 내가 어떻게 기억할 수 있겠어?"	,	"How can I remember the things you did not say?"	]	,
                 [	"내가 어디서 손을 씻을 수 있나요? (= 화장실이 어디 있나요?)"	,	"Where can I wash my hands?"	]	,
                 [	"너 누구랑 통화하고 있는거야? (전화기에 얘기하고 있니?)"	,	"Whom are you talking with on the phone?"	]	,
                 [	"너는 왜 지난 밤 그 경찰서에 있었던 거니?"	,	"Why were you at the police office last night?"	]	,
                 [	"그들이 왜 비행기에 탑승하기를 거부하고 있는 중인가요?"	,	"Why are they refusing to board the flight?"	]	,
                 [	"당신은 그 여자에게 몇 개의 e-mail을 보냈었나요?"	,	"How many emails have you sent her?"	]	,
                 [	"당신의 아내는 왜 그러한 비싼 물건들을 샀습니까?"	,	"Why did your wife buy such expensive things?"	]	,
                 [	"당신의 아이들은 어디에 머무르고 있는 중인가요?"	,	"Where are your children staying?"	]	,
                 [	"담신의 아이들은 지금까지 어떻게 지내 왔습니까?"	,	"How have your children been until now?"	]	,
                 [	"당신의 친구들은 여기 한국에 머문지 얼마나 됐습니까?"	,	"How long have your friends stayed here in Korea?"	]	,
                 [	"당신의 할아버지는 언제 여기를 떠나기를 원하시나요?"	,	"When does your grandfather want to leave here?"	]	,
                 [	"당신은 얼마 동안 이 클럽에서 노래를 부르고 있는 중인가요?"	,	"How long have you been singing in this club?"	]	,
                 [	"산꼭대기에 있는 저 거대한 성은 언제 지어졌니?"	,	"When was the huge castle which is on the top of the mountain built?"	]	,
                 [	"당신의 아기는 손에 현재 무엇을 갖고 있나요?"	,	"What does your baby have in his hand righ now?"	]	,
                 [	"당신과 친구들은 내일 뭘 할 계획인가요?"	,	"What do you and your friends plan to do tomorrow?"	]	,
                 [	"신문 첫 장에 무엇이 있나요?"	,	"What is on the first page of a newspaper?"	]	,
                 [	"안테나는 TV의 어디에 장착되어 있나요?"	,	"Where is the antenna located on the television?"	]	,
                 [	"Ray의 딸들이 언제부터 긴장하고 있었나요?"	,	"Since when have Ray's daughters been nervous?"	]	,
                 [	"너는 괜찮니?"	,	"Are you all right?"	]	,
                 [	"당신의 직장 동료들은 춤추는 것을 좋아하나요?"	,	"Do your co-workers like dancing?"	]	,
                 [	"80달러가 충분할까요?"	,	"Will eighty dollars be enough?"	]	,
                 [	"내가 영어를 배울 수 있을까?"	,	"Can I learn English?"	]	,
                 [	"Tom은 벌써 자러 갔나요?"	,	"Has Tom gone to bed already?"	]	,
                 [	"너 그 자리에 지원할래?"	,	"Will you apply for the position?"	]	,
                 [	"음~, 그가 나를 좀 도와줄 수 있나요?"	,	"Could he help me?"	]	,
                 [	"그가 서둘러 줄 수 있을까?"	,	"Can he hurry up?"	]	,
                 [	"그가 어제 학교에 없었습니까?"	,	"Wasn't he at school yesterday?"	]	,
                 [	"그것은 그의 것이 아니었나요?"	,	"Wasn't it his?"	]	,
                 [	"그녀가 신분증을 가져와야 하나요?"	,	"Should she bring her ID?"	]	,
                 [	"내가 썼나요?"	,	"Did I write?"	]	,
                 [	"그녀는 내일 콘서트에 갈 건가요?"	,	"Will she go to the concert tomorrow?"	]	,
                 [	"그것들은 Olivia의 오리들이 아니었나요?"	,	"Weren't they Olivia's ducks?"	]	,
                 [	"그녀는 일요일에 사무실에 꼭 가야만 하니?"	,	"Must she go to the office on Sunday?"	]	,
                 [	"겨울에 날씨가 눈이 많이 오지 않나요?"	,	"Dosen't it snow much in winter?"	]	,
                 [	"그녀의 개는 강에서 수영해본 적 있니?"	,	"Has her dog swum in a river?"	]	,
                 [	"그는 1964년에 태어났나요?"	,	"Was he born in 1964?"	]	,
                 [	"너는 그것을 모르니?"	,	"Don't you know that?"	]	,
                 [	"그는 그 이유를 알아야만 하나요?"	,	"Should he know the reason?"	]	,
                 [	"그는 반드시 달려야만 하니?"	,	"Must he run?"	]	,
                 [	"그는 디지털 카메라를 갖고 있니?"	,	"Does he have a digital camera?"	]	,
                 [	"그녀는 혼자 운전할 수 있나요?"	,	"Can she drive alone?"	]	,
                 [	"그들은 당신의 나라에서 유명한 배우들입니까?"	,	"Are they famous actors in your country?"	]	,
                 [	"그들은 정말 화가 났었나요?"	,	"Were they really angry?"	]	,
                 [	"그는 카페인 알레르기가 있나요?"	,	"Does he have an allergy to caffeine?"	]	,
                 [	"너는 도서관의 위치를 나에게 알려줄 수 있겠어?"	,	"Can you tell me the library's location?"	]	,
                 [	"너는 그에게 조언 좀 해줄 수 있니?"	,	"Could you give him some advice?"	]	,
                 [	"기차가 떠날 때까지 너는 여기서 기다릴 거니?"	,	"Will you wait here until the train leaves?"	]	,
                 [	"나는 먹지 않아야 하나요?"	,	"Shouldn't I eat?"	]	,
                 [	"음~, 오늘 밤 저희와 함께 하시겠어요?"	,	"Would you join us tonight?"	]	,
                 [	"날 놀리고 있는 거지?"	,	"Are you kidding me?"	]	,
                 [	"날씨가 매우 좋았나요?"	,	"Was the weather nice?"	]	,
                 [	"당신은 다른 더 많은 책들을 가지고 있지 않나요?"	,	"Don't you have any more books?"	]	,
                 [	"그는 어제 비자를 받았나요?"	,	"Did he get his visa yesterday?"	]	,
                 [	"지금 당장 나가 줄 수 있어?"	,	"Can you go out right now?"	]	,
                 [	"과거에 내가 널 울게 한 적이 있지 않았었니?"	,	"Hadn't I made you cry in the past?"	]	,
                 [	"내가 바른 일을 하고 있는 걸까?"	,	"Am I doing the right thing?"	]	,
                 [	"내 노래를 못 들었나요?"	,	"Didn't you hear my song?"	]	,
                 [	"내가 부산을 방문한 적이 있었었나요?"	,	"Had I visited Busan?"	]	,
                 [	"음~, 우리는 놀 건가요?"	,	"Would we play?"	]	,
                 [	"그녀는 공포영화를 좋이하니?"	,	"Does she like horror movies?"	]	,
                 [	"너 일본어 공부할 거니?"	,	"Will you study Japanese?"	]	,
                 [	"너는 빨간 차를 샀니?"	,	"Did you buy a red car?"	]	,
                 [	"너희 아버지는 전에 의사셨니?"	,	"Was your father a doctor before?"	]	,
                 [	"너희들은 지금까지 쭉 서울에 살고 있지 않니?"	,	"Haven't you been living in Seoul?"	]	,
                 [	"어느 누가 내 열쇠 본 적이 있나요?"	,	"Has anyone seen my key?"	]	,
                 [	"음 ~, 당신 차를 좀 빌릴 수 있을까요?"	,	"Could I borrow your car?"	]	,
                 [	"그녀는 영어 선생님이 아닌가요?"	,	"Isn't she an English teacher?"	]	,
                 [	"당신은 어제 그 일을 끝냈나요?"	,	"Did you finish the work yesterday?"	]	,
                 [	"당신은 그를 지금 사랑하는 중인가요?"	,	"Are you loving him now?"	]	,
                 [	"호텔 요금에 아침 식사가 포함되어 있나요?"	,	"Is breakfast included in the hotel fee?"	]	,
                 [	"Sally는 피아노를 연주할 수 있나요?"	,	"Can Sally play the piano?"	]	,
                 [	"외국인들도 한국어를 배우나요?"	,	"Do foreigners learn Korean?"	]	,
                 [	"당신은 Douglas씨의 아들이 아닌가요?"	,	"Aren't you the son of Mr. Douglas?"	]	,
                 [	"당신은 Eric과 함께 있었나요?"	,	"Were you with Eric?"	]	,
                 [	"당신의 아기는 책을 읽을 수 있나요?"	,	"Can your baby read a book?"	]	,
                 [	"당신의 아버지는 복통이 있으신가요?"	,	"Does your father have a stomachache?"	]	,
                 [	"들어가도 될까 모르겠네요? (아마도 가능한가요?)"	,	"Might I come in?"	]	,
                 [	"모두 다 적고 있나요?"	,	"ls everyone writing?"	]	,
                 [	"너는 네 발가락에 닿을 수 있니?"	,	"Can you touch your toess?"	]	,
                 [	"너는 박물관 쿠폰을 가지고 있니?"	,	"Do you have a museum coupon?"	]	,
                 [	"모든 빵이 이미 벌써 다 팔렸나요?"	,	"Has all the bread been sold already?"	]	,
                 [	"산타 클로스가 멋진 선물을 가지고 올까?"	,	"Will Santa Claus bring a nice gift?"	]	,
                 [	"저에게 소금 좀 건네주실래요?"	,	"Would you pass me the salt?"	]	,
                 [	"당신은 한국의 위치를 아시나요?"	,	"Do you know Korea's location?"	]	,
                 [	"오토바이를 사야 해요, 말아야 해요?"	,	"Should I buy a motorcycle or not?"	]	,
                 [	"우리가 볼 수 있나요?"	,	"Can we see?"	]	,
                 [	"이 일을 지금 당장 꼭 해야만 하나요?"	,	"Must I do this task right now?"	]	,
                 [	"이 자켓은 나에게 너무 작은가요?"	,	"Is this jacket too small for me?"	]	,
                 [	"이것은 핸드폰이니 디지털 카메라니?"	,	"Is this a cell phone or a digital camera?"	]	,
                 [	"제가 뜻하는 바를 이해하시나요?"	,	"Do you understand what I mean?"	]	,
                 [	"당신은 오늘밤 영화를 보러 가고 싶지 않으세요?"	,	"Don't you want to go to see the movie tonight?"	]	,
                 [	"그녀는 당신에게 어제 문자 메시지 보냈나요?"	,	"Did she send a text message to you yesterday?"	]	,
                 [	"그녀는 지금 이 책들을 반드시 읽어야만 하나요?(have to 사용)"	,	"Does she have to read these books now?"	]	,
                 [	"그녀는 일요일에 사무실에 꼭 가야만 하니? (have to 사용)"	,	"Does she have to go to the office on Sunday?"	]	,
                 [	"그와 그의 아내는 지난 일요일에 그들의 새 아파트로 이사했나요?"	,	"Did he and his wife finally move into their new apartment on the last Sunday?"	]	,
                 [	"당신 딸은 그녀의 숙제를 벌써 다 했나요?"	,	"Has your daughter already done her homework?"	]	,
                 [	"당신의 부모님은 그 영화를 본 적이 있으신가요?"	,	"Have your parents seen that movie?"	]	,
                 [	"당신과 당신의 남편은 세계 일주를 해 본 적이 있나요?"	,	"Have you and your husband traveled around the world?"	]	,
                 [	"당신은 그 일을 끝냈나요? (끝냈냐 안 끝냈냐 - 여부를 물어 보는 것임)"	,	"Have you finished the work?"	]	,
                 [	"당신은 나에게 지금까지도 쭉 책을 보내고 있지 않나요?"	,	"Haven't you been sending me books?"	]	,
                 [	"당신은 점심을 먹지 않았나요? (먹었나 안 먹었나- 여부를 물어보는 것임)"	,	"Haven't you eaten lunch?"	]	,
                 [	"여기 둘러봐도 될까 모르겠네요? (아마도 가능한가요?)"	,	"May I look around here?"	]	,
                 [	"제가 Smith씨에게 이야기할 수 있나 모르겠네요?(이마도 가능한가요?)"	,	"Might I speak to Mr. Smith?"	]	,
                 [	"요즘 그는 몸무게가 늘었나요? (그런가 안 그런가여부를 묻는 것임)"	,	"Has he gained weight these days?"	]	,
                 [	"음~, 우리 아이를 위하여 담배 좀 꺼주시겠습니끼?"	,	"Would you stop smoking for my kid?"	]	,
                 [	"우리가 여름 휴가 동안 네 별장을 사용해도 될까 모르겠네요? (아마도 기능한가요?)"	,	"May we use your villa during summer vacation?"	]	,
                 [	"당신은 사무실에서 기다리고 있는 그 팩스를 받았나요? (받았나, 안 받았나 여부를 묻는 것임)"	,	"Have you received that fax which you're wating for in the office?"	]	,
                 [	"David는 집에서 직장까지 매일 걷나요?"	,	"Does David walk from home to work everyday?"	]	,
                 [	"제 아이가 사탕을 좀 먹어도 될까요?"	,	"Could my child have some candies?"	]	,
                 [	"너는 지금까지 계속 그 영화 얘기하고 있니?"	,	"Have you been talking about the movie?"	]	,
                 [	"편의점은 24시간 열려있어요?"	,	"Are convenience stores open 24 hours?"	]	,
                 [	"Andy는 그녀와 함께 파티에 가야 하나요?"	,	"Should Andy go to the party with her?"	]	,
                 [	"제가 커피 좀 가져다 드릴까요?"	,	"Could I get you some coffee?"	]	,
                 [	"서울에 대해 들어 본 적이 있나요?"	,	"Have you heard about Seoul?"	]	,
                 [	"지금 밖에 비가 오고 있는 중인가요?"	,	"Is it raining outside now?"	]	,
]
//["",""],




