// 영어, 한국어 501~1000
var vocaData1000 = [
[	"dome"	,	"둥근 천장이 있는 장소, 돔"	],
[	"domain"	,	"영토, 영역"	],
[	"dominate"	,	"지배하다, 억누르다"	],
[	"dominance"	,	"우세, 지배"	],
[	"domestic"	,	"국내의, 가정 내의"	],
[	"abdomen"	,	"배, 복부"	],
[	"dormant"	,	"잠자고 있는, 휴지의"	],
[	"dormitory"	,	"기숙사"	],
[	"donate"	,	"기부하다"	],
[	"donation"	,	"기증, 기부"	],
[	"donor"	,	"기부자"	],
[	"condone"	,	"용서하다"	],
[	"pardon"	,	"용서, 사면"	],
[	"endow"	,	"부여하다, 기부하다"	],
[	"duck"	,	"오리"	],
[	"dunk shot"	,	"덩크슛"	],
[	"dump"	,	"털썩 내려놓다, 버리다"	],
[	"dumped"	,	"버려진"	],
[	"dung"	,	"똥"	],
[	"dungeon"	,	"지하 감옥"	],
[	"dub"	,	"작위를 주다, 호칭을 붙이다"	],
[	"duke"	,	"공작"	],
[	"due"	,	"부과금, 세금"	],
[	"duty"	,	"의무, 책임"	],
[	"dusk"	,	"해질녘, 황혼"	],
[	"dust"	,	"흙, 먼지"	],
[	"duct"	,	"배관"	],
[	"conduct"	,	"지휘하다, 이끌다, 행동"	],
[	"misconduct"	,	"위법행위"	],
[	"induct"	,	"들이다, 안내하다"	],
[	"deduct"	,	"빼다, 공제하다"	],
[	"abduct"	,	"유괴하다, 납치하다"	],
[	"produce"	,	"생산하다"	],
[	"reproduce"	,	"재생하다, 재현하다"	],
[	"induce"	,	"유발하다"	],
[	"introduce"	,	"소개하다, 도입하다"	],
[	"educe"	,	"(잠재 능력 등을) 끌어내다"	],
[	"educate"	,	"교육하다, 훈육하다"	],
[	"deduce"	,	"추론하다"	],
[	"reduce"	,	"감소시키다, 축소하다"	],
[	"reduction"	,	"축소, 감소, 삭감"	],
[	"durable"	,	"내구성 있는"	],
[	"endure"	,	"견디다, 지탱하다"	],
[	"damn"	,	"저주, 악담, 저주하다"	],
[	"damage"	,	"손해, 피해"	],
[	"condemn"	,	"비난하다, 규탄하다"	],
[	"depress"	,	"낙담시키다"	],
[	"depression"	,	"우울증"	],
[	"dew"	,	"이슬"	],
[	"deer"	,	"사슴"	],
[	"delicate"	,	"섬세한, 미묘한"	],
[	"desire"	,	"욕구, 갈망, 원하다"	],
[	"devour"	,	"게걸스레 먹다"	],
[	"deter"	,	"단념시키다, 그만두게 하다"	],
[	"deterrent"	,	"단념시키는"	],
[	"desk"	,	"책상"	],
[	"deck"	,	"갑판"	],
[	"deaf"	,	"귀먹은"	],
[	"deny"	,	"부정하다, 부인하다"	],
[	"defy"	,	"반항하다, 거역하다"	],
[	"deprave"	,	"타락시키다, 부패시키다"	],
[	"destroy"	,	"파괴하다"	],
[	"demolish"	,	"분쇄하다, 파괴하다"	],
[	"debris"	,	"파편, 잔해"	],
[	"deem"	,	"생각하다, 간주하다"	],
[	"redeem"	,	"되찾다, 되사다"	],
[	"redemption"	,	"상환, 되찾기"	],
[	"devout"	,	"독실한"	],
[	"delve"	,	"깊이 탐구하다"	],
[	"depart"	,	"떠나다, 출발하다"	],
[	"delay"	,	"지연시키다"	],
[	"dialogue"	,	"대화, 문답"	],
[	"divide"	,	"나누다, 분할하다"	],
[	"division"	,	"나누기, 분할"	],
[	"dividend"	,	"배당(금)"	],
[	"device"	,	"장치, 기기"	],
[	"individual"	,	"개별적인, 개개의"	],
[	"dilemma"	,	"지퇴양난, 딜레마"	],
[	"dilate"	,	"넓어지다, 팽창시키다"	],
[	"divorce"	,	"이혼"	],
[	"display"	,	"전시하다, 진열하다"	],
[	"discrepancy"	,	"불일치, 모순"	],
[	"discernible"	,	"구별할 수 있는, 인식할 수 있는"	],
[	"discontent"	,	"불평, 불만"	],
[	"dislike"	,	"싫어하다"	],
[	"disable"	,	"무능[무력]하게 하다"	],
[	"disperse"	,	"흩어지게 하다, 분산시키다"	],
[	"dispersion"	,	"분리, 분산"	],
[	"dismay"	,	"경악하게 만들다, 경악, 실망"	],
[	"dumb"	,	"말을 못 하는, 바보같은"	],
[	"dummy"	,	"견본, 모형, 모조품"	],
[	"dumdum"	,	"바보, 멍청이"	],
[	"dull"	,	"둔한, 머리가 둔한"	],
[	"dubious"	,	"의심하는"	],
[	"doubt"	,	"의심하다"	],
[	"ear"	,	"귀"	],
[	"early"	,	"일찍이, 일찍부터"	],
[	"hear"	,	"듣다"	],
[	"enter"	,	"들어가다, 입장하다"	],
[	"entry"	,	"들어감, 진출, 참가"	],
[	"entrance"	,	"들어가기, 입구, 현관"	],
[	"entity"	,	"개체, 독립체"	],
[	"entice"	,	"유혹하다, 꼬드기다"	],
[	"engage"	,	"관계를 맺다, 종사시키다"	],
[	"engagement"	,	"참여, 약혼"	],
[	"entitle"	,	"자격을 주다, 제목을 붙이다"	],
[	"environ"	,	"둘러싸다, 에워싸다"	],
[	"environment"	,	"둘러싸기, 환경"	],
[	"endeavor"	,	"노력하다, 애쓰다"	],
[	"enthusiasm"	,	"열정"	],
[	"enthusiastic"	,	"열광적인, 열렬한"	],
[	"essential"	,	"본질적인, 필수적인"	],
[	"essentially"	,	"본질적으로, 근본적으로"	],
[	"enhance"	,	"향상시키다"	],
[	"enough"	,	"충분한"	],
[	"endanger"	,	"위험에 빠뜨리다"	],
[	"enroll"	,	"등록시키다, 입학시키다"	],
[	"enrollment"	,	"등록, 입회"	],
[	"see"	,	"보다"	],
[	"seek"	,	"찾다, 구하다"	],
[	"peek"	,	"엿보다"	],
[	"sleep"	,	"잠자다"	],
[	"sleepy"	,	"졸려운"	],
[	"seep"	,	"(액체가)스며 나오다"	],
[	"deep"	,	"깊은"	],
[	"keep"	,	"유지하다, 계속하다, 보호하다"	],
[	"weep"	,	"슬퍼하다, 울다"	],
[	"week"	,	"1주"	],
[	"feel"	,	"느끼다"	],
[	"heel"	,	"발 뒤꿈치"	],
[	"heed"	,	"조심하다, 주의하다"	],
[	"bleed"	,	"피가 나다, 출혈하다"	],
[	"greed"	,	"탐욕"	],
[	"keen"	,	"날카로운, 예리한"	],
[	"essay"	,	"수필, 에세이"	],
[	"say"	,	"말하다"	],
[	"escort"	,	"호위하다"	],
[	"establish"	,	"세우다, 설립하다"	],
[	"ever"	,	"늘, 항상, 언제나"	],
[	"forever"	,	"영원히"	],
[	"every"	,	"모두, 모두의"	],
[	"even"	,	"균등한, 짝수의"	],
[	"evenly"	,	"균등하게, 평평하게"	],
[	"uneven"	,	"평평하지 않은, 불규칙한"	],
[	"evening"	,	"저녁"	],
[	"evil"	,	"나쁜, 악질의"	],
[	"devil"	,	"악마"	],
[	"inevitable"	,	"피할 수 없는"	],
[	"fair"	,	"(날씨가)맑은, 괜찮은, 공평한, 공정한, 박람회"	],
[	"job fair"	,	"공개 취직 설명회"	],
[	"affair"	,	"사건, 문제"	],
[	"fairy"	,	"요정, 공상의, 가공의"	],
[	"fairy tale"	,	"동화, 옛날이야기"	],
[	"fame"	,	"명성"	],
[	"famous"	,	"유명한"	],
[	"fan"	,	"선풍기, 부채, 바람을 일으키다"	],
[	"fancy"	,	"공상, 화려한, 근사한"	],
[	"fantasy"	,	"공상, 환상"	],
[	"infancy"	,	"유아기"	],
[	"fend"	,	"막다, 받아[막아]넘기다"	],
[	"fence"	,	"담장"	],
[	"defend"	,	"막다, 지키다, 방어하다"	],
[	"offend"	,	"화나게 하다, 위반하다"	],
[	"offensive"	,	"화나게 하는"	],
[	"ferry"	,	"나룻배, 수송하다"	],
[	"suffer"	,	"고생하다, 괴로워하다"	],
[	"fertile"	,	"기름진, 비옥한"	],
[	"fertilize"	,	"비료를 주다, 기름지게 하다"	],
[	"offer"	,	"제안하다, 제공하다"	],
[	"confer"	,	"의논하다, 수여하다"	],
[	"conference"	,	"회의, 회견"	],
[	"differ"	,	"다르다, 의견이 다르다"	],
[	"different"	,	"다른, 상이한"	],
[	"differentiate"	,	"차별화하다, 구별하다"	],
[	"defer"	,	"연기하다, 미루다, 양보하다"	],
[	"deference"	,	"복종, 존경"	],
[	"reference"	,	"참조, 참고, 조회"	],
[	"infer"	,	"추론하다"	],
[	"inference"	,	"추리, 추론"	],
[	"prefer"	,	"더 좋아하다, 선호하다"	],
[	"transfer"	,	"바꿔타다, 옮기다"	],
[	"fly"	,	"날다"	],
[	"flight"	,	"비행, 비상"	],
[	"flag"	,	"깃발, 기"	],
[	"flake"	,	"얇고 작은 조각, 파편"	],
[	"flimsy"	,	"부서지기 쉬운"	],
[	"flute"	,	"플루트"	],
[	"flutter"	,	"펄럭이다, 휘날리다"	],
[	"fluff"	,	"보풀, 솜 부스러기"	],
[	"flee"	,	"달아나다"	],
[	"fleet"	,	"함대"	],
[	"flea"	,	"벼룩"	],
[	"fling"	,	"내던지다"	],
[	"flip"	,	"톡 튀기다"	],
[	"flap"	,	"퍼덕거리다"	],
[	"flick"	,	"가볍게 치다, 털다"	],
[	"fluctuate"	,	"오르내리다"	],
[	"fluctuation"	,	"변동"	],
[	"flump"	,	"쿵하고 떨어지다"	],
[	"flunk"	,	"낙제하다"	],
[	"floor"	,	"바닥"	],
[	"flood"	,	"홍수, 잠기게 하다"	],
[	"fluid"	,	"유체, 유동성의"	],
[	"flux"	,	"흐름, 유동"	],
[	"influx"	,	"유입"	],
[	"flex"	,	"굽히다"	],
[	"flexible"	,	"구부리기 쉬운, 유연한"	],
[	"flush"	,	"배수, 씻어 내다"	],
[	"fluent"	,	"거침없이 흐르는, 유창한"	],
[	"influence"	,	"영향을 주다, 영향"	],
[	"influential"	,	"영향력 있는"	],
[	"influenza"	,	"독감"	],
[	"float"	,	"떠다니다"	],
[	"flesh"	,	"고기, 살"	],
[	"flavor"	,	"맛, 풍미"	],
[	"flat"	,	"납작한, 평면, 아파트"	],
[	"flat tire"	,	"펑크난 타이어"	],
[	"flatter"	,	"아첨하다, 아부하다"	],
[	"deflate"	,	"수축시키다, 공기를 빼다"	],
[	"inflate"	,	"팽창하다, 부풀리다"	],
[	"inflation"	,	"인플레이션, 팽창"	],
[	"reflect"	,	"반사하다"	],
[	"conflict"	,	"대립하다, 충돌하다"	],
[	"inflict"	,	"고통을 가하다"	],
[	"afflict"	,	"괴롭히다"	],
[	"affliction"	,	"고통, 고뇌"	],
[	"flower"	,	"꽃"	],
[	"flour"	,	"밀가루"	],
[	"flora"	,	"식물군"	],
[	"florist"	,	"꽃집 주인, 꽃집"	],
[	"flourish"	,	"번영하다"	],
[	"forward"	,	"앞으로, 앞쪽에"	],
[	"forth"	,	"앞으로"	],
[	"afford"	,	"여유가 있다, 할 수 있다"	],
[	"affordable"	,	"(가격 등이)알맞은, 적당한"	],
[	"forgive"	,	"용서하다"	],
[	"forget"	,	"과거를 잊다, 잊어버리다"	],
[	"forget"	,	"위조하다, 만들다"	],
[	"fork"	,	"포크"	],
[	"folk"	,	"민속(의) 민간의, 사람들"	],
[	"forefather"	,	"선조, 조상"	],
[	"foresee"	,	"예견하다, 내다보다"	],
[	"foreseeable"	,	"미리 알 수 있는"	],
[	"unforeseen"	,	"예측하지 못한"	],
[	"forecast"	,	"예측하다, 예보하다"	],
[	"forest"	,	"숲"	],
[	"foremost"	,	"맨 앞의, 일류의"	],
[	"foreman"	,	"우두머리"	],
[	"forearm"	,	"팔뚝"	],
[	"forefinger"	,	"집게 손가락"	],
[	"forehead"	,	"이마"	],
[	"fort"	,	"요새"	],
[	"fortify"	,	"요새화하다, 강화하다"	],
[	"fortress"	,	"요새, 요새지"	],
[	"fortune"	,	"재산, 행운"	],
[	"misfortune"	,	"불운, 불행, 역경"	],
[	"fortunate"	,	"운이 좋은"	],
[	"comfort"	,	"위로하다, 격려하다"	],
[	"effort"	,	"노력, 수고"	],
[	"force"	,	"힘"	],
[	"airforce"	,	"공군"	],
[	"enforce"	,	"시행하다, 실시하다"	],
[	"reinforce"	,	"강화하다, 증강하다"	],
[	"reinforcement"	,	"강화, 증강, 보강"	],
[	"form"	,	"모양, 형태, 형성시키다"	],
[	"foam"	,	"거품"	],
[	"formal"	,	"공식적인, 격식을 차린"	],
[	"formation"	,	"구조, 조립"	],
[	"formula"	,	"공식"	],
[	"deform"	,	"(모양 등을) 변형하다"	],
[	"inform"	,	"알리다, 통지하다"	],
[	"information"	,	"정보, 자료, 지식"	],
[	"informative"	,	"정보를 주는, 유익한"	],
[	"conform"	,	"순응하다, 따르다"	],
[	"conformity"	,	"순종, 일치, 적합"	],
[	"reform"	,	"고치다, 개혁하다, 개정하다"	],
[	"perform"	,	"행하다, 수행하다"	],
[	"performance"	,	"연주, 연기, 공연"	],
[	"uniform"	,	"제복, 군복, 유니폼"	],
[	"firm"	,	"강한, 굳은, 확고한, 기업"	],
[	"affirm"	,	"단언하다, 확언하다"	],
[	"confirm"	,	"확실하게 하다"	],
[	"reconfirm"	,	"재확인하다"	],
[	"infirm"	,	"약한, 허약한"	],
[	"fragile"	,	"깨지기 쉬운, 망가지기 쉬운"	],
[	"fragment"	,	"조각, 파편"	],
[	"fragmentary"	,	"단편적인"	],
[	"fragrance"	,	"방향, 향기"	],
[	"front"	,	"맨 앞 부분, 앞면"	],
[	"frontier"	,	"국경, 경계, 개척자"	],
[	"forefront"	,	"선봉, 최전선"	],
[	"confront"	,	"직면하다"	],
[	"affront"	,	"모욕하다"	],
[	"fact"	,	"시실, 진실"	],
[	"factor"	,	"요소, 요인"	],
[	"factory"	,	"공장"	],
[	"manufacture"	,	"생산하다, 제조하다"	],
[	"manufacturer"	,	"제조회사"	],
[	"facility"	,	"시설, 설비"	],
[	"facilitate"	,	"가능(용이)하게 하다"	],
]