// 영어, 한국어 1501~2000
var vocaData2000 = [
["outbreak", "발생, 발발"],
["outage", "정전, 단수"],
["output", "생산, 산출물"],
["outlet", "배출구, 판로, 직판장"],
["outdo", "뛰어나다"],
["outlive", "오래살다"],
["overhead", "머리 위에, 하늘 높이"],
["overpower", "앞도하다"],
["overtax", "지나치게 과세하다"],
["overcoat", "외투, 오버코트"],
["overlap", "겹치다"],
["oversee", "감독하다"],
["overdue", "기한이 지난"],
["overlook", "못보고 넘어가다, 눈감아 주다"],
["overshadow", "가리다"],
["overall", "전부, 전체의"],
["pan", "손잡이가 달린 얇은 냄비(팬)"],
["pancake", "팬케이크"],
["company", "회사, 일행, 중대"],
["panorama", "전경, 광대한 조망"],
["span", "한 뼘, 범위"],
["expand", "확장하다"],
["expansive", "팽창력이 있는, 넒은, 광대한"],
["expansion", "확장, 팽창"],
["parade", "나란히 걸아가다, 가두 행진"],
["parent", "부모"],
["apparent", "명백한"],
["appear", "나타나다"],
["disappear", "사라지다, 모습을 감추다"],
["transparent", "투명한"],
["compare", "비교하다"],
["comparable", "비교할 수 있는"],
["prepare", "준비하다"],
["apparel", "옷"],
["parliament", "의회, 국회"],
["parrot", "앵무새"],
["parody", "패더리"],
["paradox", "역설, 모순"],
["parallel", "평행선"],
["parachute", "낙하산"],
["apparatus", "장치, 기구"],
["separate", "분리하다, 떼어 놓다"],
["paradise", "낙원"],
["pair", "한 쌍"],
["impair", "손상시키다"],
["repair", "수리하다, 고치다"],
["repairman", "수리공"],
["irreparable", "회복할 수 없는"],
["despair", "절망, 실망, 낙담"],
["desperate", "절망적인, 필사적인"],
["part", "부분"],
["apart", "떨어져, 따로따로"],
["partner", "파트너"],
["party", "파티, 모임"],
["participate", "참가하다"],
["particular", "개별적인, 특별한"],
["particularly", "두드러지게, 특히"],
["counterpart", "복사, 사본"],
["depart", "출발하다"],
["particle", "미량, 작은 조각"],
["parcel", "소포, 꾸러미"],
["partial", "일부분의, 부분적인"],
["impartial", "공정한, 공평한"],
["pass", "지나가다, 통과하다"],
["passive", "수동적인, 소극적인"],
["passenger", "승객"],
["compass", "순회하다"],
["bypass", "우회로"],
["underpass", "지하도"],
["overpass", "육교"],
["surpass", "초월하다, 넘다"],
["passion", "격렬한 감정, 열정"],
["compassion", "연민"],
["pathetic", "불쌍한, 측은한, 감상적인"],
["telepathy", "텔레파시"],
["sympathy", "공감"],
["propel", "추진하다, 나아가게 하다"],
["propeller", "프로펠러"],
["compel", "억지로 시키다, 무리하게 시키다"],
["repel", "거절하다"],
["expel", "내쫓다, 쫓아버리다"],
["dispel", "없애다"],
["pulse", "맥박"],
["impulse", "충동"],
["compulsory", "의무적인, 강제적인"],
["appeal", "간청, 애원"],
["pendant", "부속물, 늘어뜨린 장식"],
["depend", "의지하다"],
["independence", "독립"],
["appendix", "부록"],
["suspend", "보류하다"],
["impend", "임박하다"],
["spend", "쓰다, 소비하다"],
["dispensable", "불필요한"],
["indispensable", "필수의"],
["expend", "소비하다, 소모하다"],
["compensate", "보상하다"],
["perfect", "완벽한"],
["percent", "퍼센트, 100분"],
["perfume", "향수"],
["fume", "연기, 가스"],
["person", "사람됨, 사람, 인품"],
["personnel", "전체 직원"],
["personal", "개인적인"],
["perish", "소멸하다, 사라지다"],
["permanent", "영원한, 오래가는"],
["persuade", "설득하다"],
["plaza", "광장"],
["plat", "땅 한 뙈기"],
["platform", "승강장, 플랫폼"],
["plaster", "회반죽"],
["plate", "접시"],
["place", "장소, 놓아두다"],
["misplace", "잘못 놓다"],
["replace", "대신하다, 교체하다"],
["displace", "옮기다, 대신하다"],
["plan", "계획"],
["airplane", "비행기"],
["planet", "행성"],
["plain", "평야, 단순한, 분명한, 쉬운"],
["explain", "상세히 설명하다"],
["complain", "불평하다, 투덜대다"],
["plant", "심다, 식물"],
["implant", "깊이 새기다, 심다"],
["supplant", "대신하다"],
["plenty", "많음, 다량"],
["mutiple", "다수의, 복합의"],
["mutiply", "곱하다, 증가시키다"],
["deplete", "고갈시키다"],
["complete", "전부의, 완전한"],
["imcomplete", "불완전한, 불충분한"],
["complement", "보충물, 보완물"],
["compliment", "칭찬하다"],
["supplement", "보충물, 추가물"],
["implement", "도구, 연장"],
["complex", "컴플렉스"],
["complicate", "복잡하게 하다, 뒤얽히게 하다"],
["implicate", "암시하다, 포함하다, 내포하다"],
["duplicate", "복제하다"],
["accomplish", "성취하다"],
["comply", "따르다"],
["reply", "대답하다"],
["apply", "적용하다"],
["applicant", "응모자, 신청자"],
["employ", "고용하다"],
["employer", "고용주"],
["employee", "종업원"],
["monopoly", "독점, 전매"],
["plus", "더하여"],
["surplus", "여분, 나머지"],
["popcorn", "팝콘"],
["popsong", "팝송, 대중가요"],
["popular", "인기있는"],
["popularity", "인기, 유행"],
["population", "인구"],
["pub", "선술집"],
["public", "공중인, 대중의"],
["publish", "발행하다, 발표하다"],
["port", "항구"],
["portable", "휴대용의"],
["porter", "짐꾼"],
["portal", "대문, 통로, 포탈"],
["porch", "현관"],
["portfolio", "휴대용 서류가방"],
["portrait", "초상화"],
["portion", "부분, 몫"],
["proportion", "비율"],
["airport", "공항"],
["passport", "여권"],
["transport", "수송하다, 옮기다"],
["import", "수입하다"],
["important", "중요한"],
["export", "수출하다"],
["deport", "추방하다, 강제로 이송하다"],
["report", "보고서"],
["reporter", "신문기자, 보고자"],
["support", "버티다, 지탱하다"],
["opportunity", "기회"],
["print", "인쇄하다"],
["pride", "긍지, 자부심"],
["proud", "자랑으로 여기는, 자신에 찬"],
["spring", "봄, 뛰어 오름"],
["sprout", "자라기 시작하다, 발아하다, 새싹"],
["sprite", "요정"],
["sprint", "단거리 경주, 전력질주, 전속력으로 달리다"],
["sprinkle", "뿌리다"],
["spray", "물보라, 분사하다"],
["spread", "펴다"],
["widespread", "넓게 편"],
["prevalence", "널리퍼짐, 유행"],
["preach", "설교하다"],
["premium", "상급의, 상질의"],
["premier", "국무총리, 수상, 최고의"],
["preliminary", "예비의, 준비의"],
["previous", "앞의, 앞선, 사전의"],
["priority", "우선순위"],
["problem", "문제"],
["prominent", "눈에 띄는, 탁월한"],
["protrude", "튀어나오다"],
["prompt", "즉각적인"],
["protocol", "규약"],
["prophecy", "예언"],
["proximity", "가까움"],
["prosper", "번영하는"],
["province", "도, 주"],
["prosecute", "기소하다"],
["prove", "입증하다, 증명하다"],
["improve", "개량하다, 개선하다"],
["approve", "승인하다"],
["disapproval", "불찬성, 불만"],
["prime", "가장 중요한, 주된, 제 1의"],
["primary", "주요한, 기본적인"],
["primitive", "본원의, 근본의, 원시의"],
["prince", "왕자, 왕손"],
["princess", "공주"],
["principal", "교장"],
["principle", "원칙"],
["price", "값, 가격"],
["prize", "상, 상품"],
["precious", "값비싼, 귀중한"],
["appreciate", "진가를 인정하다, 감사하다"],
["appreciable", "주목할 만한"],
["depreciate", "가치를 떨어뜨리다, 멸시하다"],
["private", "사적인, 개인적인"],
["deprive", "박탈하다"],
["privilege", "특권"],
["press", "누르다"],
["pressure", "압력, 압박, 부담"],
["compress", "압축하다, 압착하다"],
["oppress", "억압하다, 탄압하다"],
["suppress", "억제하다, 진압하다"],
["depress", "낙담시키다, 약하게 하다"],
["express", "표현하다, 고속의"],
["impression", "인상"],
["prison", "교도소"],
["prisoner", "죄수"],
["surprise", "놀라게 하다"],
["enterprise", "기업, 회사"],
["comprise", "포함하다"],
["special", "특수한, 특별한"],
["specialist", "전문가, 전공자"],
["species", "종업원"],
["specimen", "견본, 표본"],
["spectacle", "관경, 장관"],
["spectator", "구경꾼, 관람객, 목격자"],
["speculate", "깊이 생각하다"],
["specific", "특별한, 명확한, 분명한"],
["aspect", "측면, 국면"],
["suspect", "의심하다"],
["inspect", "조사하다, 정검하다"],
]
