// 영어, 한국어 1501~2000
var vocaData2000 = [
["outbreak", "발생, 발발"],
["outage", "정전, 단수"],
["output", "생산, 산출물"],
["outlet", "배출구, 판로, 직판장"],
["outdo", "뛰어나다"],
["outlive", "오래살다"],
["overhead", "머리 위에, 하늘 높이"],
["overpower", "앞도하다"],
["overtax", "지나치게 과세하다"],
["overcoat", "외투, 오버코트"],
["overlap", "겹치다"],
["oversee", "감독하다"],
["overdue", "기한이 지난"],
["overlook", "못보고 넘어가다, 눈감아 주다"],
["overshadow", "가리다"],
["overall", "전부, 전체의"],
["pan", "손잡이가 달린 얇은 냄비(팬)"],
["pancake", "팬케이크"],
["company", "회사, 일행, 중대"],
["panorama", "전경, 광대한 조망"],
["span", "한 뼘, 범위"],
["expand", "확장하다"],
["expansive", "팽창력이 있는, 넒은, 광대한"],
["expansion", "확장, 팽창"],
["parade", "나란히 걸아가다, 가두 행진"],
["parent", "부모"],
["apparent", "명백한"],
["appear", "나타나다"],
["disappear", "사라지다, 모습을 감추다"],
["transparent", "투명한"],
["compare", "비교하다"],
["comparable", "비교할 수 있는"],
["prepare", "준비하다"],
["apparel", "옷"],
["parliament", "의회, 국회"],
["parrot", "앵무새"],
["parody", "패더리"],
["paradox", "역설, 모순"],
["parallel", "평행선"],
["parachute", "낙하산"],
["apparatus", "장치, 기구"],
["separate", "분리하다, 떼어 놓다"],
["paradise", "낙원"],
["pair", "한 쌍"],
["impair", "손상시키다"],
["repair", "수리하다, 고치다"],
["repairman", "수리공"],
["irreparable", "회복할 수 없는"],
["despair", "절망, 실망, 낙담"],
["desperate", "절망적인, 필사적인"],
["part", "부분"],
["apart", "떨어져, 따로따로"],
["partner", "파트너"],
["party", "파티, 모임"],
["participate", "참가하다"],
["particular", "개별적인, 특별한"],
["particularly", "두드러지게, 특히"],
["counterpart", "복사, 사본"],
["depart", "출발하다"],
["particle", "미량, 작은 조각"],
["parcel", "소포, 꾸러미"],
["partial", "일부분의, 부분적인"],
["impartial", "공정한, 공평한"],
["pass", "지나가다, 통과하다"],
["passive", "수동적인, 소극적인"],
["passenger", "승객"],
["compass", "순회하다"],
["bypass", "우회로"],
["underpass", "지하도"],
["overpass", "육교"],
["surpass", "초월하다, 넘다"],
["passion", "격렬한 감정, 열정"],
["compassion", "연민"],
["pathetic", "불쌍한, 측은한, 감상적인"],
["telepathy", "텔레파시"],
["sympathy", "공감"],
["propel", "추진하다, 나아가게 하다"],
["propeller", "프로펠러"],
["compel", "억지로 시키다, 무리하게 시키다"],
["repel", "거절하다"],
["expel", "내쫓다, 쫓아버리다"],
["dispel", "없애다"],
["pulse", "맥박"],
["impulse", "충동"],
["compulsory", "의무적인, 강제적인"],
["appeal", "간청, 애원"],
["pendant", "부속물, 늘어뜨린 장식"],
["depend", "의지하다"],
["independence", "독립"],
["appendix", "부록"],
["suspend", "보류하다"],
["impend", "임박하다"],
["spend", "쓰다, 소비하다"],
["dispensable", "불필요한"],
["indispensable", "필수의"],
["expend", "소비하다, 소모하다"],
["compensate", "보상하다"],
["perfect", "완벽한"],
["percent", "퍼센트, 100분"],
["perfume", "향수"],
["fume", "연기, 가스"],
]
