// 영어, 한국어 1001~1500
var vocaData1500 = [
["shirt", "셔츠"], // 1001
["sheet","시트 홑이불"],
["shell","껍질, 외피"],
["shelter","피난처"],
["shield","방패"],
["sheriff","보안관"],
["shackle","수갑, 족쇄"],
["shoulder","어깨"],
["shroud","수의, 가리다"],
["shallow","얕은, 표면적인"],
["shore","해안, 물가"],
["sheep","양"],
["shepherd","양치기"],
["shape","모습, 모양"],
["shade","그늘"],
["shadow","그림자"],
["share","몫, 할당"],
["shareholder","주주"],
["shabby","닳아 해진, 누더기의"],
["shame","부끄럼"],
["shampoo","샴푸"],
["white","흰색"],
["whole","전체의, 모든, 온전한"],
["whale","고래"],
["wheel","바퀴"],
["wheelchair","휠체어"],
["wheelbarrow","외바퀴 손수레"],
["high","높은"],
["height","높이"],
["highlight","중요부분"],
["highway","고속도로"],
["hierarchy","계급제, 서열"],
["hill","언덕"],
["hike","도보여행"],
["initial","처음의"],
["initiate","시작하다"],
["input","투입량"],
["indulge","빠지다, 탐닉하다"],
["injure","부상을 입다[입히다]"],
["indoor","실내의"],
["intake","섭취"],
["intimate","친밀한"],
["industry","산업, 제조업"],
["income","수입"],
["index","색인, 지표"],
["ink","잉크"],
["internet","인터넷"],
["interval","(시간적) 간격"],
["integrate","통합하다"],
["disintegrate","해체하다, 붕괴시키다"],
["integral","(전체의 일부로서) 필수적인"],
["integrity","진실성, 고결"],
["intrinsic","본질적인"],
["interest","관심"],
["intrude","침범하다"],
["intestine","내장"],
["intricate","복잡한"],
["interpret","통역하다"],
["interior","안쪽의, 내부의, 인테리어"],
["deteriorate","악화되다, 더 나빠지다"],
["jet","분출, 분출하다"],
["jet plane","제트기"],
["jet lag","시차증"],
["jetty","둑, 부두"],
["project","계획, 설계"],
["projector","영사기, 기획자, 설계자"],
["subject","신하, 부하"],
["subjective","주관적인"],
["reject","거절하다"],
["rejection","거절"],
["eject","탈출하다, 쫓아내다"],
["object","반대하다, 사물, 물건"],
["injection","주입, 주사"],
["join","합류하다, 결합하다"],
["adjoin","결합하다, 인접하다"],
["enjoin","명하다"],
["joint","접합부분, 이음매"],
["junction","접합, 결합"],
["conjunction","연합, 연대, 접속사"],
["jump","뛰다, 뛰어오르다"],
["junior","나이가 어린, 연하의 사람"],
["juvenile","청소년"],
["jubilant","환성을 지르는"],
["juice","주스"],
["juicy","즙이많은"],
["junk","폐물"],
["jumble","마구 뒤섞이다"],
["jungle","정글"],
["juggle","저글링하다"],
["judge","판결을내리다"],
["judgement","재판"],
["adjudge","결정하다, 선고하다"],
["judicial","사법의, 재판의"],
["judicious","사려깊은, 현명한"],
["prejudice","편견, 선입관"],
["jury","배심원"],
["jurisdiction","사법, 사법권"],
["perjury","위증,"],
["just","정의, 올바른, 꼭, 바로"],
["justice","정의, 공정"],
["justify","정당화하다"],
["justified","정당화된"],
["injustice","불공정"],
["adjust","맞추다, 정비하다"],
["kid","아이"],
["kidnap","유괴하다"],
["kidney","콩팥, 신장"],
["kit","한세트 , 한벌"],
["kitten","새끼고양이"],
["kite","연"],
["kin","친족, 친척"],
["kinship","친척관계"],
["akin","동족의, 혈족의"],
["kind","종류, 친절"],
["kindergarten","유치원"],
["king","왕"],
["kint","짜다"],
["knot","매듭, 결합"],
["knob","손잡이"],
["knock","두드리다"],
["knack","솜씨, 묘기"],
["knuckle","손가락 관절"],
["knee","무릅 관절"],
["kneel","무릅을 꿇다, 굴복하다"],
["know","알다, 이해하다"],
["knowledge","지식"],
["acknowledge","인정하다, 승인하다"],
["noble","귀족의, 고귀한"],
["knife","칼"],
["skin","피부, 살갗, 가죽"],
["ski","스키"],
["skill","솜씨, 기술"],
["skillful","숙련된"],
["sky","하늘"],
["skitter","(수면을) 스쳐날다"],
["skip","가볍게 건너뛰다, 거르다"],
["skid","미끄러지다"],
["skim","스치듯 지나가다"],
["skate","스케이트"],
["sketch","스케치"],
["skirt","밖으로 퍼진 가장자리, 치마"],
["outskirt","변두리, 교외"],
["skeleton","해골"],
["sculpture","조각, 조각술"],
["skeptical","의심많은, 회의적인"],
["labor","일하다, 노동, 근로"],
["laboratory","실험실, 연구소"],
["laborious","열심히 일하는, 근면한"],
["elaborate","공들이다, 정교한"],
["collaborate","공동으로 작업하다, 협력하다"],
["collaboration","협력, 협동"],
["logo","상표"],
["logic","논리"],
["apology","사과"],
["monolog","독백, 1인극"],
["dialogue","대화"],
["catalogue","목록,카탈로그"],
["epilogue","맺음말"],
["biology","생물학"],
["ecology","생태학"],
["zoology","동물학"],
["psychology","심리학"],
["language","언어"],
["slang","속어, 슬랭"],
["lingua","혀"],
["lingual","혀의, 언어의"],
["bilingual","2개 국어를 말하는"],
["linguistics","언어학"],
["legend","전설, 레전드"],
["legacy","유산"],
["college","대학"],
["colleague","동료"],
["legion","군단, 부대"],
["diligent","부지런한, 근면한"],
["inteligent","지성을 가진, 영리한"],
["negligent","태만한, 부주의한, 게으른"],
["eligible","자격이 있는"],
["legal","법률의, 합법적인"],
["illegal","불법적인"],
["ligislate","법률을 제정하다, 입법하다"],
["legislation","법률 제정"],
["legislature","입법부"],
["privilege","특권"],
["allege","주장하다"],
["delegate","위임하다, 대리인, 대표자"],
["delegation","대표로 임명, 대표단"],
["lever","제렛대, 지레"],
["leverage","영향력, 지레의 작용"],
["elevate","올리다, 향상시키다"],
["elevator","엘리베이터, 승강기"],
["elevation","높이, 고도"],
["level","평평한, 평탄한"],
["relieve","부담을 덜어주다, 경감하다"],
["relevant","관계가 있는"],
["irrelevant","관계가 없는, 부적절한"],
["light","빛, 가벼운"],
["lightning","번개"],
["enlighten","계몽하다, 가르치다"],
["flight","비행"],
["twilight","해질녁, 석양, 황혼"],
["ignite","점화하다, 불을 붙이다"],
["slight","약간의, 조금의, 경미한"],
["bright","빛나는"],
["brilliant","눈부신, 찬란한"],
["delight","기쁘게하다, 기쁨, 즐거움"],
["local","현지의"],
["locate","장소를 알아내다, 자리잡다"],
["location","위치, 장소"],
["allocation","할당, 배분"],
["dislocate","위치를 바꾸다"],
["relocate","재배치하다"],
["lock","잠그다, 자물쇠"],
["unlock","자물쇠를 풀다"],
["locker","사물함"],
["interlock","서로 맞물리게 하다"],
["flock","떼, 떼를 이루다"],
["block","막다"],
["blocking","방해[저지]하는 것"],
["long","긴"],
["belong","속하다"],
["prolong","길어지다, 지속되다"],
["longstanding","다년간의, 오랫동안에 걸친"],
["longevity","장수"],
["length","길이, 기간"],
["lengthen","길게 하다"],
["longitude","경도"],
["latitude","위도"],
["lot","제비(뽑기), 할당된 몫"],
["lottery","복권, 추첨, 제비 뽑기"],
["allot","배당하다, 할당하다"],
["slot","가늘고 길쭉한 구멍"],
["plot","줄거리, 음모"],
["blot","얼룩, 더러움, 흠"],
["clot","응고하다, 엉긴 덩어리"],
["split","쪼개다, 나누다"],
["slice","얇은조각, 자르다"],
["late","늦은"],
["lately","최근에"],
["translate","번역하다"],
["relate","이야기하다, 관계시키다"],
["related","관계있는, 연관된"],
["relative","관계가 있는, 상대적인, 친척"],
["collect","수집하다, 모으다"],
["collective","모인, 집합적인"],
["recollect","회상하다"],
["select","고르다, 선발하다"],
["intellect","지성, 지력"],
["lecture","강의"],
["neglect","등한시하다, 무시하다"],
["elect","선출하다"],
["liberal","자유주의의, 진보적인, 개혁적인"],
["liberate","자유롭게 하다"],
["library","도서관"],
["deliberate","신중히 생각하다"],
["deliver","배달하다"],
["slide","미끄러지다"],
["sled","썰매, 썰매를 타다"],
["glide","활주하다"],
["collide","충돌하다"],
["low","아래쪽, 낮은"],
["lower","낮추다"],
["flow","흐르다"],
["slow","느린, 더딘"],
["plow","쟁기"],
["allow","허락하다, 허가하다"],
["disallow","금하다"],
["slip","미끄러지다"],
["slipper","실내화, 슬리퍼"],
["slope","경사, 비탈"],
["sleep","잠을자다"],
["sleeve","소매"],
["slim","호리호리한"],
["slime","슬쩍빠져나가다"],
["slender","갸냘픈, 가느다란"],
["slam","쾅 닫힌다, 쾅 닫다"],
["slate","슬레이트"],
["mankind","인류"],
["manager","경영자, 관리인"],
["managerial","관리의, 경영의"],
["manicure","매니큐어"],
["manner","방법, 태도"],
["manual","교본, 손을쓰는"],
["manifest","일목요연한, 분명한"],
["maniqulate","잘 다루다, 조작하다"],
["mantle","덮게, 망토"],
["dismantle","제거하다, 철거하다"],
["command","명령하다"],
["mandate","위임하다"],
["mandatory","의무적인"],
["demand","요구하다"],
["demanding","요구가 지나친"],
["middle","한가운데의, 중간의"],
["medium","중간의, 보통의"],
["media","대중매체"],
["mediate","중재하다. 조정하다"],
["intermediate","중간의"],
["meditate","숙고하다, 계획하다"],
["medicine","약"],
["medical","의학의, 의료의"],
["remedy","치료(약)"],
["immediate","즉시의"],
["medieval","중세의"],
["mediterranean","지중해의"],
["model","표준, 기준"],
["modern","현대의, 요즈음의"],
["commode","서랍장"],
["commodity","일용품, 필수품"],
["accommodate","공간을 제공하다, 수용하다"],
["modify","수정하다, 변경하다"],
["moderate","온건한, 보통의, 적절한"],
["modest","알맞은, 겸손한"],
["memorandum","메모, (사건따위의)기록"],
["memoir","회고록"],
["memory","메모리, 기억, 회상"],
["memorable","기억할 만한"],
["memorial","기념물, 추모비, 추모의"],
["commemorate","기념하다"],
["remember","생각해내다, 상기하다"],
["member","구성원"],
["amend","개정하다, 개선하다"],
["commend","칭찬하다"],
["recommend","추천하다"],
["mini","작은, 소형의"],
["minimal","최소한의"],
["minimum","최소한도, 최소량"],
["minimize","최소한도로 하다"],
["minify","작게하다, 최소로 만들다"],
["minister","장관, 각료, 성직자, 봉사하다"],
["administer","집행하다, 관리하다"],
["diminish","줄이다, 작게하다"],
["permit","허락하다"],
["commit","위임하다, 맡기다, 약속하다"],
["commitment","공약, 서약, 책임"],
["committee","위원회"],
["transmit","전송하다"],
["remit","보내다, 부치다"],
["submit","상납하다, 복종하다, 제출하다"],
["submission","굴복, 순종, 제출"],
["omit","생략하다"],
["emit","발산하다, 배출하다"],
["emission","발산, 방사"],
["admit","들어오게 하다, 인정하다"],
["admission","들어가기, 입장, 입학, 인정하기"],
["missile","미사일"],
["mission","임무"],
["intermission","휴게시간"],
["dismiss","해산시키다, 해고하다"],
["message","메시지, 알림"],
["promise","약속, 약속하다"],
["compromise","타협하다"],
["promising","유망한"],
["premise","전제, 가정"],
["premises","부지"],
["motor","모터"],
["motorcycle","오토바이"],
["motion","움직임, 운동, 운행"],
["motionless","정지하고 있는"],
["emotion","감정"],
["motive","동기"],
["motivate","동기를 부여하다, 자극하다"],
["promote","촉진하다, 장려하다, 승진시키다"],
["remote","먼, 멀리 떨어진"],
["mainstream","주류, 본류"],
["mainframe","본체"],
["maintain","유지하다"],
["maintenance","유지, 지속"],
["remain","살아남다, 남다"],
["major","주요한, 중요한, 큰, 대다수의"],
["majority","대다수, 대부분"],
["majesty","위엄, 존엄, 장대함"],
["mayor","시장"],
["magnify","확대하다, 크게보이게하다"],
["magnificent","장대한, 화려한"],
["magnitude","대량, 방대, 큼"],
["maxim","격언, 금언"],
["maximum","최대한, 최대량"],
["megaphone","확성기, 메가폰"],
["megabox","매우 큰 극장"],
["imminent","임박한, 곧 일어날 것 같은"],
["eminent","저명한, 탁월한"],
["preeminent","뛰어난"],
["prominent","두드러진, 눈에 띄는"],
["mount","산, 오르다, 타다"],
["mountain","산"],
["amount","총계"],
["surmount","극복하다"],
["mound","둔덕, 언덕"],
["neck","목"],
["connect","결합시키다, 접속시키다"],
["connection","결합, 관련, 관계"],
["disconnection","접속을 끊다, 차단하다"],
["next","다음의"],
["nexus","유대, 관계"],
["annex","병합하다, 부과하다"],
["nothing","아무것도 없음"],
["noon","정오, 한낮"],
["noxious","유독한"],
["nod","끄덕이다"],
["nonfiction","전기, 실화, 역사기록"],
["nonsense","넌센스, 허튼소리"],
["negro","흑인"],
["negative","부정적인, 반대의"],
["negotiate","협상하다, 협의하다"],
["neglect","방치하다, 무시하다"],
["negligible","무시할 수 있는, 사소한"],
["negligence","태만, 등한"],
["never","절대로 아니다"],
["nevertheless","그럼에도 불구하고"],
["neutral","중립적인"],
["need","필요하다"],
["needle","바늘"],
["nude","벗은"],
["nut","견과류"],
["nuclear","핵의, 원자력의"],
["norm","기준, 표준"],
["normal","표준적인, 보통의, 정상적인"],
["normalize","표준화시키다, 기준에 맞추다"],
["subnormal","보통 이하의, 정신 박약의"],
["abnormal","이상한, 정신 이상의"],
["enormous","거대한, 엄청난"],
["snow","눈"],
["snake","뱀"],
["snatch","잡아채다"],
["snare","덫"],
["snag","그루터기"],
["snap","딱 소리내다"],
["nation","나라, 국가"],
["international","국제적인"],
["native","태어난 땅의, 모국의"],
["nature","자연"],
["natural","자연의"],
["supernatural","초자연의, 불가사의한"],
["innate","타고난, 천부적인"],
["connate","타고난, 선천적인"],
["novel","소설"],
["novelty","참신함, 새로움, 신기함"],
["novice","풋나기"],
["renovate","혁신하다, 수리하다"],
["innovate","쇄신하다, 혁신하다"],
["nova","별"],
["note","기록, 수기, 노트"],
["notion","개념, 관념"],
["notify","통지하다, 알리다"],
["notebook","공책"],
["notation","표기법, 표시법"],
["annotaion","주석, 주해"],
["notable","주목할 만한, 중요한"],
["notice","알아차리다, 주목"],
["notorious","악명 높은"],
["announce","알리다, 발표하다"],
["announcer","아나운서"],
["pronounce","발음하다"],
["denounce","비난하다"],
["nurse","간호사"],
["nursery","탁아소, 아이방"],
["nurture","양육하다"],
["nutrition","영양, 영양공급"],
["nourish","영양분을 주다, 기르다"],
["object","반대하다, 목표. 대상"],
["obstacle","장애물"],
["obscure","분명하지 않은, 애매한"],
["obesity","비만, 과체중"],
["obey","복종하다"],
["disobedient","반항적인"],
["opera","오페라"],
["operate","움직이다, 작동하다"],
["operative","효력이 있는"],
["inoperative","효력이 없는"],
["cooperate","협력하다"],
["optic","눈의, 시력의"],
["optics","광학"],
["optical","시력을 돕는, 눈에 의한"],
["opportunity","기회"],
["option","선택하다"],
["adopt","입양하다, 채택하다"],
["adoption","입양, 채용, 채택"],
["opinion","의견"],
["optimum","최적조건"],
["optimism","낙천주의, 낙관"],
["optimistic","낙관적인"],
["optimize","최대한활용하다"],
["oral","구두의, 입의"],
["moral","도덕의, 윤리상의"],
["immoral","부도덕한"],
["morale","사기"],
["demoralize","사기를 꺽다, 의기소침하게하다"],
["order","명령, 순서, 규칙"],
["ordinary","보통의, 통상적인"],
["extraordinary","비상한, 비범한"],
["disorder","무질서"],
["coordinate","조정하다, 조직화하다"],
["coordinator","조정자"],
["coordination","통일, 조화"],
["subordinate","종속하는, 하위의"],
["orient","동쪽"],
["origin","기원, 유래"],
["original","원래의, 최초의"],
["originate","일어나다, 발원하다, 시작되다"],
["outline","윤곽, 외형선"],
["outlook","조망, 경치"]
]
