// 영어, 한국어 1~500
var vocaData0500 = [
["ball", "둥근것, 공"],
["balloon", "풍선, 기구"],
["bell", "종, 벨"],
["belly", "불룩한 배"],
["bullet", "총알"],
["bulb", "전구, 둥근뿌리"],
["bulk", "큰 규모, 육중한 것"],
["base", "바닥, 기초, 기지"],
["basic", "기초적인, 근본적인"],
["basement", "지하층, 지하실"],
["baseball", "야구"],
["bass", "저음, 베이스"],
["blouse", "블라우스(옷)"],
["blout", "부풀다, 붓다"],
["blister", "물집"],
["blowfish", "복어"],
["blow", "불다"],
["blur", "흐릿해지다"],
["blind", "눈이 먼"],
["bluff", "허풍"],
["bubble", "거품"],
["bud", "싹, 꽃봉오리"],
["budget", "예산"],
["bun", "동그랗고 작은 빵"],
["bunch", "송이(포도 따위의), 다발"],
["buy", "사다"],
["bury", "묻어 놓다"],
["burp", "트림, 트림소리"],
["ban", "막다, 금지하다"],
["banish", "추방하다, 몰아내다"],
["band", "묶다(끈 등으로), 반창고, 띠, 무리"],
["bandit", "노상강도"],
["husband", "남편"],
["abandon", "포기하다, 버리다"],
["bandage", "붕대"],
["bind", "묶다"],
["bond", "유대, 결속, 접착제"],
["bound", "한계, 경계"],
["boundary", "국경, 경계"],
["bundle", "다발, 꾸러미"],
["bar", "가로막다, 빗장, 막대기"],
["bartender", "바(술집)에서 일하는 사람"],
["bargain", "흥정하다, 거래"],
["barn", "헛간"],
["barrel", "불룩한 통"],
["barrier", "장애물, 울타리"],
["barricade", "장벽, 방책, 바리케이드"],
["embarrass", "당황하게 하다"],
["embargo", "통상금지"],
["barren", "불모의, 척박한"],

["bat", "때리다, (공을)치다"],
["battle", "전투, 싸움"],
["bate", "줄이다, 약하게하다"],
["abate", "감소시키다, 줄이다, 완화하다"],
["debate", "논쟁하다, 토론하다"],
["beat", "(아주 세게 계속)때리다, 이기다"],
["bicycle", "자전거"],
["bias", "편견"],
["alibi", "알리바이, 변명"],
["bilingual", "2개 국어를 말하는"],
["binoculars", "쌍안경"],
["bisect", "양분하다, 이등분하다"],
["biology", "생물학"],
["antibiotic", "항생물질, 항생제"],
["biography", "전기, 일대기"],
["bloom", "꽃이 피다"],
["black", "검은, 검은색"],
["blank", "비어 있는, 백지의, 빈칸"],
["blanket", "담요"],
["bleach", "표백하다, 희게하다"],
["blade", "칼날, 날"],
["bleed", "피를 흘리다"],
["blaze", "불타다"],
["ablaze", "불길에 휩싸인"],
["blizzard", "심한 눈보라, 폭설"],
["bless", "축복하다"],
["blast", "폭발하다, 폭파"],
["bluster", "(파도가)거세게 몰아치다, 고함치다"],
["burst", "폭발하다, 폭발"],
["blare", "크게 울려 퍼지다"],
["blond", "금발"],
["break", "깨뜨리다, 부수다"],
["breakfast", "아침식사"],
["breakage", "파손, 손상"],
["breakthrough", "돌파구"],
["broker", "중매인, 중개인"],
["broach", "송곳(통에 구멍내는)"],
["breach", "터진 구멍, 위반, 침해"],
["brick", "벽돌"],
["brisk", "활발한, 기운찬"],
["brittle", "깨지기 쉬운, 부서지기 쉬운"],
["briquette", "연탄, 조개탄"],
["broad", "넓은"],
["board", "널빤지, 판자"],
["aboard", "승선하여, (배, 비행기 등을)타고"],
["breadth", "너비, 폭, 폭넓음"],
["breath", "호흡"],
["boil", "끓이다"],
["broil", "굽다"],

["brief", "간단한, 잠시 동안의"],
["abbreviate", "단축하다, 생략하다"],
["abroad", "해외로, 외국에[으로]"],
["able", "할 수 있는, 능력 있는, 유능한"],
["ability", "능력, 역량"],
["enable", "가능[용이]하게 하다"],
["abolish", "없애다, 폐지하다"],
["abnormal", "이상한, 보통과 다른"],
["abort", "낙태하다, 유산시키다"],
["abuse", "남용하다"],
["absurd", "터무니 없는, 우스꽝스러운, 불합리한"],
["absorb", "빨아들이다, 흡수하다"],
["absolute", "절대적인, 완전한"],
["absolve", "사면하다, 풀어주다, (죄를)용서하다"],
["absent", "부재의, 결석의, 없는"],
["abrupt", "갑작스러운, 뜻밖의"],
["circle", "원, 원둘레"],
["encircle", "둘러싸다, 에워싸다"],
["circulate", "순환하다"],
["circus", "서커스"],
["circumstance", "(주변의)상황, 환경"],
["cycle", "순환, 반복, 주기"],
["bicycle", "자전거"],
["recycle", "재활용하다"],
["cyclone", "큰 회오리 바람, 대폭풍"],
["cab", "택시, 마차"],
["cabin", "오두막집, 통나무집"],
["cabinet", "수납장, 장식 선반"],
["cabana", "오두막집, (해변 등의)간의 탈의실"],
["cubic", "정육면체의, 입체의"],
["cubicle", "좁은 방(큰 방 한쪽을 칸막이 해 만든)"],
["can", "통, 용기, 관"],
["cane", "줄기(대나무.사탕수수 등의), 지팡이"],
["candy", "사탕"],
["cannon", "대포"],
["canyon", "협곡"],
["canal", "운하"],
["channel", "해협, 수로, 경로, 루트"],
["cap", "모자"],
["capsule", "작은통, 캡슐"],
["capacity", "수용 인원, 수용력"],
["capacious", "널찍한, 큼직한"],
["capable", "유능한, 할 수 있는"],
["captain", "대장, 선장"],
["capital", "수도, 대문자, 자본"],
["cape", "망토"],
["escape", "달아나다, 도망가다"],
["handicap", "불리한 조건, 장애"],
["capsize", "뒤집히다"],
["capture", "붙잡다, 포획하다"],
["captive", "포로, 인질"],

["caption", "표제, 제목"],
["precept", "격언, 계율, 교훈"],
["concept", "개념"],
["misconception", "오해, 착각"],
["susceptible", "민감한, 예민한"],
["accept", "받아들이다, 승낙하다"],
["reception", "수령, 응접, 접수, 환영(회)"],
["receptionist", "접수 담당자(호텔, 사무실, 병원 등의)"],
["receipt", "영수증"],
["except", "제외하는 바는~"],
["exception", "제외, 예외"],
["exceptional", "예외적인, 매우 뛰어난"],
["excerpt", "발췌, 인용구"],
["deception", "속임수, 기만"],
["intercept", "가로채다"],
["recipe", "조리법"],
["aniticipate", "예상하다, 기대하다"],
["disciple", "제자, 문하생"],
["discipline", "훈련, 훈육, 규율, 학과목"],
["precipitate", "재촉하다, 촉진시키다"],
["principal", "교장"],
["reciprocal", "상호의, 서로의"],
["principle", "원칙, 법칙"],
["participate", "참여하다, 참가하다"],
["occupy", "차지하다, 점유하다"],
["preoccupy", "먼저 점유하다, 선취하다, 마음을 빼앗다, 몰두하게 하다"],
["preoccupied", "몰두한, 열중한, 정신이 팔린"],
["car", "차, 마차, 자동차"],
["cargo", "화물"],
["carpenter", "목수"],
["cart", "손수레"],
["carton", "(운송용)판지 상자, 종이 상자"],
["carry", "운반하다, 가지고[들고] 가다"],
["carrier", "운송이, 수송[운송] 회사"],
["carriage", "마차, (기차의)객차, 운송, 수송"],
["career", "경력"],
["charisma", "비범한 통솔력"],
["carve", "조각하다"],
["charge", "충전하다, 채우다, (책임을)지우다"],
["discharge", "짐을 내리다, 방출하다, 퇴원하다, 해고하다"],
["curve", "곡선"],
["curl", "(형태가) 곱슬곱슬한 머리카락"],
["current", "현재의, 통용되는(유통되고 있는), 흐름"],
["currency", "통화(화폐), 통용"],
["concurrent", "동시 발생의, 공존하는"],
["course", "진로, 방향, 과정"],
["incur", "초래하다"],
["incursion", "침입, 급습"],
["occur", "(일이)생기다, 일어나다"],
["recur", "다시 일어나다, 되풀이 되다"],
  
["curb", "억제[제한]하다"],
["curfew", "통행금지령, 통행금지 시간, 귀가 시간"],
["curtain", "커튼, 휘장"],
["excursion", "나들이, 소풍, 견학"],
["concur", "동의하다, 의견이 일치하다"],
["care", "돌보다, 마음[신경]을 쓰다, 주의, 걱정, 관심"],
["careful", "주의 깊은, 조심스러운, 세심한"],
["careless", "부주의한, 신중하지 않은"],
["precarious", "위태로운, 불완전한"],
["charity", "기부, 자선, 구호"],
["cherish", "소중히 여기다"],
["childish", "어린 아이의"],
["cure", "치료, 의료, 치료법"],
["curative", "치료의, 치료 효험이 있는"],
["curator", "전시기획자, (박물관등의)관리자"],
["manicure", "메니큐어를 하다, 다듬다"],
["secure", "안전한, 안전하게 하다"],
["insecure", "불안한, 자신이 없는"],
["rescue", "구조하다, 구출하다"],
["obscure", "애매한, 분명하지 않은"],
["accurate", "정확한, 정밀한"],
["inaccurate", "부정확한"],
["cause", "근거, 이유, 원인"],
["caution", "주의, 조심, 경계"],
["cautious", "조심스러운, 신중한"],
["precaution", "예방조치, 사전대책"],
["excuse", "변명하다, 변명, 핑계"],
["accuse", "고발하다, 비난하다"],
["cover", "덮다, 가리다, 보호하다"],
["coverage", "(보험의) 보호, 보상범위"],
["discover", "발견하다"],
["recover", "회복하다, 되찾다"],
["succeed", "성공하다"],
["success", "성공"],
["successive", "연속하는"],
["proceed", "나아가다, 진행하다"],
["process", "(일련의) 과정, 공정"],
["procedure", "절차"],
["precede", "선행하다"],
["exceed", "초과하다, 능가하다, 넘어서다"],
["excess", "초과"],
["excessive", "지나친, 과도한"],
["recede", "물러나다[가다], 철회하다"],
["recess", "휴회, 휴식시간"],
["recession", "경기 후퇴, 불경기"],
["antecedent", "선행사건, 선행하는, 선조"],
["ancestor", "조상, 선조"],
["access", "접근, 가까이 다가감"],
["accessible", "접근할 수 있는, 이용 가능한"],
["inaccessible", "접근하기 어려운"],

["accessory", "부속물, 액세서리"],
["necessary", "필요한"],
["necessitate", "필요로 하다"],
["predecessor", "전임자, 선배"],
["cease", "중지하다, 끝내다"],
["ceaseless", "중단없는, 끊임없는"],
["decease", "사망하다"],
["accident", "우연한 일, 사고"],
["accidental", "우발적인, 뜻하지 않은"],
["incident", "사건, 사고"],
["incidental", "부수적으로 일어나는"],
["receive", "받다, 수령하다"],
["perceive", "인지하다, 이해하다"],
["conceive", "임신하다, 상상하다"],
["deceive", "속이다"],
["deceitful", "기만하는, 속이는"],
["cell", "독방, 작은 방, 세포"],
["cellar", "지하 저장실"],
["conceal", "감추다"],
["ceiling", "천장"],
["celestial", "하늘의, 천체의"],
["celebrate", "축하하다, 기념하다"],
["celebrity", "유명인사"],
["excel", "뛰어나다, 능가하다"],
["excellent", "뛰어난, 우수한"],
["accelerate", "가속하다"],
["cent", "1센트 동전"],
["centimeter", "센티미터"],
["century", "100년, 1세기"],
["innocent", "무죄의, 순수한"],
["innocence", "순수, 결백"],
["decent", "충분히 좋은, 알맞은"],
["chief", "우두머리"],
["chef", "주방장"],
["mischief", "해악, 못된 짓"],
["achieve", "성취하다, 이루다"],
["handkerchief", "손수건"],
["decide", "결정하다"],
["decided", "명확한, 분명한"],
["decisive", "결정적인, 결단력 있는"],
["suicide", "자살"],
["insecticide", "살충, 살충제"],
["pesticide", "농약"],
["scissors", "가위"],
["concise", "간결한"],
["precise", "정확한"],
["exercise", "운동, 연습"],
["cite", "인용하다, 예로 들다"],
["recital", "암송, 독주회"],
["incite", "자극하다, 격려하다"],
]
