// 영어, 한국어 501~1000
var vocaData1000 = [
[	"dome"	,	"둥근 천장이 있는 장소, 돔"	],
[	"domain"	,	"영토, 영역"	],
[	"dominate"	,	"지배하다, 억누르다"	],
[	"dominance"	,	"우세, 지배"	],
[	"domestic"	,	"국내의, 가정 내의"	],
[	"abdomen"	,	"배, 복부"	],
[	"dormant"	,	"잠자고 있는, 휴지의"	],
[	"dormitory"	,	"기숙사"	],
[	"donate"	,	"기부하다"	],
[	"donation"	,	"기증, 기부"	],
[	"donor"	,	"기부자"	],
[	"condone"	,	"용서하다"	],
[	"pardon"	,	"용서, 사면"	],
[	"endow"	,	"부여하다, 기부하다"	],
[	"duck"	,	"오리"	],
[	"dunk shot"	,	"덩크슛"	],
[	"dump"	,	"털썩 내려놓다, 버리다"	],
[	"dumped"	,	"버려진"	],
[	"dung"	,	"똥"	],
[	"dungeon"	,	"지하 감옥"	],
[	"dub"	,	"작위를 주다, 호칭을 붙이다"	],
[	"duke"	,	"공작"	],
[	"due"	,	"부과금, 세금"	],
[	"duty"	,	"의무, 책임"	],
[	"dusk"	,	"해질녘, 황혼"	],
[	"dust"	,	"흙, 먼지"	],
[	"duct"	,	"배관"	],
[	"conduct"	,	"지휘하다, 이끌다, 행동"	],
[	"misconduct"	,	"위법행위"	],
[	"induct"	,	"들이다, 안내하다"	],
[	"deduct"	,	"빼다, 공제하다"	],
[	"abduct"	,	"유괴하다, 납치하다"	],
[	"produce"	,	"생산하다"	],
[	"reproduce"	,	"재생하다, 재현하다"	],
[	"induce"	,	"유발하다"	],
[	"introduce"	,	"소개하다, 도입하다"	],
[	"educe"	,	"(잠재 능력 등을) 끌어내다"	],
[	"educate"	,	"교육하다, 훈육하다"	],
[	"deduce"	,	"추론하다"	],
[	"reduce"	,	"감소시키다, 축소하다"	],
[	"reduction"	,	"축소, 감소, 삭감"	],
[	"durable"	,	"내구성 있는"	],
[	"endure"	,	"견디다, 지탱하다"	],
[	"damn"	,	"저주, 악담, 저주하다"	],
[	"damage"	,	"손해, 피해"	],
[	"condemn"	,	"비난하다, 규탄하다"	],
[	"depress"	,	"낙담시키다"	],
[	"depression"	,	"우울증"	],
[	"dew"	,	"이슬"	],
[	"deer"	,	"사슴"	],
[	"delicate"	,	"섬세한, 미묘한"	],
[	"desire"	,	"욕구, 갈망, 원하다"	],
[	"devour"	,	"게걸스레 먹다"	],
[	"deter"	,	"단념시키다, 그만두게 하다"	],
[	"deterrent"	,	"단념시키는"	],
[	"desk"	,	"책상"	],
[	"deck"	,	"갑판"	],
[	"deaf"	,	"귀먹은"	],
[	"deny"	,	"부정하다, 부인하다"	],
[	"defy"	,	"반항하다, 거역하다"	],
[	"deprave"	,	"타락시키다, 부패시키다"	],
[	"destroy"	,	"파괴하다"	],
[	"demolish"	,	"분쇄하다, 파괴하다"	],
[	"debris"	,	"파편, 잔해"	],
[	"deem"	,	"생각하다, 간주하다"	],
[	"redeem"	,	"되찾다, 되사다"	],
[	"redemption"	,	"상환, 되찾기"	],
[	"devout"	,	"독실한"	],
[	"delve"	,	"깊이 탐구하다"	],
[	"depart"	,	"떠나다, 출발하다"	],
[	"delay"	,	"지연시키다"	],
[	"dialogue"	,	"대화, 문답"	],
[	"divide"	,	"나누다, 분할하다"	],
[	"division"	,	"나누기, 분할"	],
[	"dividend"	,	"배당(금)"	],
[	"device"	,	"장치, 기기"	],
[	"individual"	,	"개별적인, 개개의"	],
[	"dilemma"	,	"지퇴양난, 딜레마"	],
[	"dilate"	,	"넓어지다, 팽창시키다"	],
[	"divorce"	,	"이혼"	],
[	"display"	,	"전시하다, 진열하다"	],
[	"discrepancy"	,	"불일치, 모순"	],
[	"discernible"	,	"구별할 수 있는, 인식할 수 있는"	],
[	"discontent"	,	"불평, 불만"	],
[	"dislike"	,	"싫어하다"	],
[	"disable"	,	"무능[무력]하게 하다"	],
[	"disperse"	,	"흩어지게 하다, 분산시키다"	],
[	"dispersion"	,	"분리, 분산"	],
[	"dismay"	,	"경악하게 만들다, 경악, 실망"	],
[	"dumb"	,	"말을 못 하는, 바보같은"	],
[	"dummy"	,	"견본, 모형, 모조품"	],
[	"dumdum"	,	"바보, 멍청이"	],
[	"dull"	,	"둔한, 머리가 둔한"	],
[	"dubious"	,	"의심하는"	],
[	"doubt"	,	"의심하다"	],
[	"ear"	,	"귀"	],
[	"early"	,	"일찍이, 일찍부터"	],
[	"hear"	,	"듣다"	],
[	"enter"	,	"들어가다, 입장하다"	],
[	"entry"	,	"들어감, 진출, 참가"	],
[	"entrance"	,	"들어가기, 입구, 현관"	],
[	"entity"	,	"개체, 독립체"	],
[	"entice"	,	"유혹하다, 꼬드기다"	],
[	"engage"	,	"관계를 맺다, 종사시키다"	],
[	"engagement"	,	"참여, 약혼"	],
[	"entitle"	,	"자격을 주다, 제목을 붙이다"	],
[	"environ"	,	"둘러싸다, 에워싸다"	],
[	"environment"	,	"둘러싸기, 환경"	],
[	"endeavor"	,	"노력하다, 애쓰다"	],
[	"enthusiasm"	,	"열정"	],
[	"enthusiastic"	,	"열광적인, 열렬한"	],
[	"essential"	,	"본질적인, 필수적인"	],
[	"essentially"	,	"본질적으로, 근본적으로"	],
[	"enhance"	,	"향상시키다"	],
[	"enough"	,	"충분한"	],
[	"endanger"	,	"위험에 빠뜨리다"	],
[	"enroll"	,	"등록시키다, 입학시키다"	],
[	"enrollment"	,	"등록, 입회"	],
[	"see"	,	"보다"	],
[	"seek"	,	"찾다, 구하다"	],
[	"peek"	,	"엿보다"	],
[	"sleep"	,	"잠자다"	],
[	"sleepy"	,	"졸려운"	],
[	"seep"	,	"(액체가)스며 나오다"	],
[	"deep"	,	"깊은"	],
[	"keep"	,	"유지하다, 계속하다, 보호하다"	],
[	"weep"	,	"슬퍼하다, 울다"	],
[	"week"	,	"1주"	],
[	"feel"	,	"느끼다"	],
[	"heel"	,	"발 뒤꿈치"	],
[	"heed"	,	"조심하다, 주의하다"	],
[	"bleed"	,	"피가 나다, 출혈하다"	],
[	"greed"	,	"탐욕"	],
[	"keen"	,	"날카로운, 예리한"	],
[	"essay"	,	"수필, 에세이"	],
[	"say"	,	"말하다"	],
[	"escort"	,	"호위하다"	],
[	"establish"	,	"세우다, 설립하다"	],
[	"ever"	,	"늘, 항상, 언제나"	],
[	"forever"	,	"영원히"	],
[	"every"	,	"모두, 모두의"	],
[	"even"	,	"균등한, 짝수의"	],
[	"evenly"	,	"균등하게, 평평하게"	],
[	"uneven"	,	"평평하지 않은, 불규칙한"	],
[	"evening"	,	"저녁"	],
[	"evil"	,	"나쁜, 악질의"	],
[	"devil"	,	"악마"	],
[	"inevitable"	,	"피할 수 없는"	],
[	"fair"	,	"(날씨가)맑은, 괜찮은, 공평한, 공정한, 박람회"	],
[	"job fair"	,	"공개 취직 설명회"	],
[	"affair"	,	"사건, 문제"	],
[	"fairy"	,	"요정, 공상의, 가공의"	],
[	"fairy tale"	,	"동화, 옛날이야기"	],
[	"fame"	,	"명성"	],
[	"famous"	,	"유명한"	],
[	"fan"	,	"선풍기, 부채, 바람을 일으키다"	],
[	"fancy"	,	"공상, 화려한, 근사한"	],
[	"fantasy"	,	"공상, 환상"	],
[	"infancy"	,	"유아기"	],
[	"fend"	,	"막다, 받아[막아]넘기다"	],
[	"fence"	,	"담장"	],
[	"defend"	,	"막다, 지키다, 방어하다"	],
[	"offend"	,	"화나게 하다, 위반하다"	],
[	"offensive"	,	"화나게 하는"	],
[	"ferry"	,	"나룻배, 수송하다"	],
[	"suffer"	,	"고생하다, 괴로워하다"	],
[	"fertile"	,	"기름진, 비옥한"	],
[	"fertilize"	,	"비료를 주다, 기름지게 하다"	],
[	"offer"	,	"제안하다, 제공하다"	],
[	"confer"	,	"의논하다, 수여하다"	],
[	"conference"	,	"회의, 회견"	],
[	"differ"	,	"다르다, 의견이 다르다"	],
[	"different"	,	"다른, 상이한"	],
[	"differentiate"	,	"차별화하다, 구별하다"	],
[	"defer"	,	"연기하다, 미루다, 양보하다"	],
[	"deference"	,	"복종, 존경"	],
[	"reference"	,	"참조, 참고, 조회"	],
[	"infer"	,	"추론하다"	],
[	"inference"	,	"추리, 추론"	],
[	"prefer"	,	"더 좋아하다, 선호하다"	],
[	"transfer"	,	"바꿔타다, 옮기다"	],
[	"fly"	,	"날다"	],
[	"flight"	,	"비행, 비상"	],
[	"flag"	,	"깃발, 기"	],
[	"flake"	,	"얇고 작은 조각, 파편"	],
[	"flimsy"	,	"부서지기 쉬운"	],
[	"flute"	,	"플루트"	],
[	"flutter"	,	"펄럭이다, 휘날리다"	],
[	"fluff"	,	"보풀, 솜 부스러기"	],
[	"flee"	,	"달아나다"	],
[	"fleet"	,	"함대"	],
[	"flea"	,	"벼룩"	],
[	"fling"	,	"내던지다"	],
[	"flip"	,	"톡 튀기다"	],
[	"flap"	,	"퍼덕거리다"	],
[	"flick"	,	"가볍게 치다, 털다"	],
[	"fluctuate"	,	"오르내리다"	],
[	"fluctuation"	,	"변동"	],
[	"flump"	,	"쿵하고 떨어지다"	],
[	"flunk"	,	"낙제하다"	],
[	"floor"	,	"바닥"	],
[	"flood"	,	"홍수, 잠기게 하다"	],
[	"fluid"	,	"유체, 유동성의"	],
[	"flux"	,	"흐름, 유동"	],
[	"influx"	,	"유입"	],
[	"flex"	,	"굽히다"	],
[	"flexible"	,	"구부리기 쉬운, 유연한"	],
[	"flush"	,	"배수, 씻어 내다"	],
[	"fluent"	,	"거침없이 흐르는, 유창한"	],
[	"influence"	,	"영향을 주다, 영향"	],
[	"influential"	,	"영향력 있는"	],
[	"influenza"	,	"독감"	],
[	"float"	,	"떠다니다"	],
[	"flesh"	,	"고기, 살"	],
[	"flavor"	,	"맛, 풍미"	],
[	"flat"	,	"납작한, 평면, 아파트"	],
[	"flat tire"	,	"펑크난 타이어"	],
[	"flatter"	,	"아첨하다, 아부하다"	],
[	"deflate"	,	"수축시키다, 공기를 빼다"	],
[	"inflate"	,	"팽창하다, 부풀리다"	],
[	"inflation"	,	"인플레이션, 팽창"	],
[	"reflect"	,	"반사하다"	],
[	"conflict"	,	"대립하다, 충돌하다"	],
[	"inflict"	,	"고통을 가하다"	],
[	"afflict"	,	"괴롭히다"	],
[	"affliction"	,	"고통, 고뇌"	],
[	"flower"	,	"꽃"	],
[	"flour"	,	"밀가루"	],
[	"flora"	,	"식물군"	],
[	"florist"	,	"꽃집 주인, 꽃집"	],
[	"flourish"	,	"번영하다"	],
[	"forward"	,	"앞으로, 앞쪽에"	],
[	"forth"	,	"앞으로"	],
[	"afford"	,	"여유가 있다, 할 수 있다"	],
[	"affordable"	,	"(가격 등이)알맞은, 적당한"	],
[	"forgive"	,	"용서하다"	],
[	"forget"	,	"과거를 잊다, 잊어버리다"	],
[	"forget"	,	"위조하다, 만들다"	],
[	"fork"	,	"포크"	],
[	"folk"	,	"민속(의) 민간의, 사람들"	],
[	"forefather"	,	"선조, 조상"	],
[	"foresee"	,	"예견하다, 내다보다"	],
[	"foreseeable"	,	"미리 알 수 있는"	],
[	"unforeseen"	,	"예측하지 못한"	],
[	"forecast"	,	"예측하다, 예보하다"	],
[	"forest"	,	"숲"	],
[	"foremost"	,	"맨 앞의, 일류의"	],
[	"foreman"	,	"우두머리"	],
[	"forearm"	,	"팔뚝"	],
[	"forefinger"	,	"집게 손가락"	],
[	"forehead"	,	"이마"	],
[	"fort"	,	"요새"	],
[	"fortify"	,	"요새화하다, 강화하다"	],
[	"fortress"	,	"요새, 요새지"	],
[	"fortune"	,	"재산, 행운"	],
[	"misfortune"	,	"불운, 불행, 역경"	],
[	"fortunate"	,	"운이 좋은"	],
[	"comfort"	,	"위로하다, 격려하다"	],
[	"effort"	,	"노력, 수고"	],
[	"force"	,	"힘"	],
[	"airforce"	,	"공군"	],
[	"enforce"	,	"시행하다, 실시하다"	],
[	"reinforce"	,	"강화하다, 증강하다"	],
[	"reinforcement"	,	"강화, 증강, 보강"	],
[	"form"	,	"모양, 형태, 형성시키다"	],
[	"foam"	,	"거품"	],
[	"formal"	,	"공식적인, 격식을 차린"	],
[	"formation"	,	"구조, 조립"	],
[	"formula"	,	"공식"	],
[	"deform"	,	"(모양 등을) 변형하다"	],
[	"inform"	,	"알리다, 통지하다"	],
[	"information"	,	"정보, 자료, 지식"	],
[	"informative"	,	"정보를 주는, 유익한"	],
[	"conform"	,	"순응하다, 따르다"	],
[	"conformity"	,	"순종, 일치, 적합"	],
[	"reform"	,	"고치다, 개혁하다, 개정하다"	],
[	"perform"	,	"행하다, 수행하다"	],
[	"performance"	,	"연주, 연기, 공연"	],
[	"uniform"	,	"제복, 군복, 유니폼"	],
[	"firm"	,	"강한, 굳은, 확고한, 기업"	],
[	"affirm"	,	"단언하다, 확언하다"	],
[	"confirm"	,	"확실하게 하다"	],
[	"reconfirm"	,	"재확인하다"	],
[	"infirm"	,	"약한, 허약한"	],
[	"fragile"	,	"깨지기 쉬운, 망가지기 쉬운"	],
[	"fragment"	,	"조각, 파편"	],
[	"fragmentary"	,	"단편적인"	],
[	"fragrance"	,	"방향, 향기"	],
[	"front"	,	"맨 앞 부분, 앞면"	],
[	"frontier"	,	"국경, 경계, 개척자"	],
[	"forefront"	,	"선봉, 최전선"	],
[	"confront"	,	"직면하다"	],
[	"affront"	,	"모욕하다"	],
[	"fact"	,	"시실, 진실"	],
[	"factor"	,	"요소, 요인"	],
[	"factory"	,	"공장"	],
[	"manufacture"	,	"생산하다, 제조하다"	],
[	"manufacturer"	,	"제조회사"	],
[	"facility"	,	"시설, 설비"	],
[	"facilitate"	,	"가능(용이)하게 하다"	],
[	"facsimile"	,	"팩스"	],
[	"faculty"	,	"능력, 재능"	],
[	"perfect"	,	"완벽한"	],
[	"infect"	,	"감염시키다"	],
[	"infectious"	,	"전염성의"	],
[	"defect"	,	"결점, 단점, 약점"	],
[	"defective"	,	"결점이 있는"	],
[	"affect"	,	"영향을 미치다"	],
[	"affection"	,	"애정, 애착"	],
[	"effect"	,	"결과, 효과"	],
[	"effectively"	,	"효과적으로"	],
[	"ineffective"	,	"효과가 없는"	],
[	"efficient"	,	"능률적인, 효율적인"	],
[	"face"	,	"얼군, 면"	],
[	"facet"	,	"자른 단면"	],
[	"surface"	,	"표면, 외면"	],
[	"preface"	,	"서문"	],
[	"interface"	,	"상호작용 영역, 접속기"	],
[	"efface"	,	"사라지게 하다, 지우다"	],
[	"fiction"	,	"소설, 꾸며낸 이야기"	],
[	"office"	,	"사무실"	],
[	"officer"	,	"장교, 경찰관"	],
[	"deficit"	,	"적자, 부족액"	],
[	"deficient"	,	"부족한, 결핍되어있는"	],
[	"artificial"	,	"인공의"	],
[	"superficial"	,	"피상적인"	],
[	"sufficient"	,	"충분한"	],
[	"proficient"	,	"숙달된, 능숙한"	],
[	"efficient"	,	"능률적인, 효율적인"	],
[	"difficult"	,	"어려운"	],
[	"traffic"	,	"교통(흐름), 통행"	],
[	"certificate"	,	"증명서"	],
[	"qualify"	,	"자격을 주다"	],
[	"disqualified"	,	"자격을 잃은"	],
[	"satisfy"	,	"만족시키다"	],
[	"satisfaction"	,	"만족, 흡족"	],
[	"dissatisfaction"	,	"불만, 불평"	],
[	"magnify"	,	"확대하다"	],
[	"fit"	,	"적당한, 알맞은"	],
[	"outfit"	,	"외출 옷"	],
[	"benefit"	,	"이득, 혜택"	],
[	"profit"	,	"이익, 수익"	],
[	"fund"	,	"바닥, 기초, 자금"	],
[	"fund-raiser"	,	"자금 조달자"	],
[	"refund"	,	"환불하다, 상환하다"	],
[	"fundamental"	,	"기본적인, 근본적인"	],
[	"founder"	,	"설립자"	],
[	"foundation"	,	"(건물의) 토대, 기반, 근거, 재단, (화장품) 파운데이션"	],
[	"profound"	,	"심오한, 깊은"	],
[	"fountain"	,	"분수"	],
[	"fuse"	,	"녹이다"	],
[	"fusion"	,	"용해, 융합"	],
[	"unfuse"	,	"주입하다"	],
[	"diffuse"	,	"분산시키다, 발산하다"	],
[	"confuse"	,	"혼동하다"	],
[	"refuse"	,	"거절하다"	],
[	"gene"	,	"유전자"	],
[	"genom"	,	"유전체"	],
[	"genetic"	,	"유전의, 발생의"	],
[	"generate"	,	"발생시키다"	],
[	"degenerate"	,	"퇴보하다, 타락하다"	],
[	"generator"	,	"발전기"	],
[	"generation"	,	"세대"	],
[	"genre"	,	"종류, 유형, 장르"	],
[	"general"	,	"포괄적인, 일반적인, 장군"	],
[	"generous"	,	"관대한, 너그러운"	],
[	"gentle"	,	"온화한, 부드러운"	],
[	"gentleman"	,	"신사"	],
[	"genial"	,	"상냥한, 온화한"	],
[	"congenial"	,	"마음이 맞는"	],
[	"genesis"	,	"기원, 발생, 창시"	],
[	"genius"	,	"천재성, 천재"	],
[	"ingenious"	,	"독창적인, 기발한"	],
[	"genuine"	,	"진품의, 진짜의"	],
[	"congenital"	,	"타고난"	],
[	"gender"	,	"성별"	],
[	"agenda"	,	"의제, 협의사항"	],
[	"engine"	,	"엔진"	],
[	"engineer"	,	"엔지니어, 기술자"	],
[	"gesture"	,	"몸짓, 손짓, 동작"	],
[	"suggest"	,	"제안하다"	],
[	"congest"	,	"혼잡하다"	],
[	"congestion"	,	"혼잡"	],
[	"digest"	,	"소화하다"	],
[	"register"	,	"기록하다, 등록하다"	],
[	"glass"	,	"유리"	],
[	"gloss"	,	"광택을 내다"	],
[	"glitter"	,	"반짝이다"	],
[	"glow"	,	"빛나다"	],
[	"glory"	,	"영광"	],
[	"glad"	,	"밝은, 즐거운"	],
[	"gleam"	,	"희미하게 빛나다"	],
[	"glance"	,	"흘낏보다"	],
[	"glare"	,	"노려보다"	],
[	"diagnose"	,	"진단하다"	],
[	"diagnosis"	,	"진찰, 진단"	],
[	"cognitive"	,	"인식"	],
[	"pregnant"	,	"임신한"	],
[	"recognize"	,	"인정하다, 알아보다"	],
[	"ignore"	,	"무시하다"	],
[	"grin"	,	"방긋 웃다"	],
[	"grow"	,	"성장하다, 자라다"	],
[	"growth"	,	"성장, 발육"	],
[	"grain"	,	"곡물"	],
[	"grind"	,	"갈다"	],
[	"grass"	,	"풀, 잔디"	],
[	"grazing"	,	"방목, 목초지"	],
[	"group"	,	"모임, 그룹"	],
[	"greet"	,	"인사, 인사하다"	],
[	"grumble"	,	"불평하다, 투덜거리다"	],
[	"growl"	,	"으르렁거리다"	],
[	"groan"	,	"신음, 신음하다"	],
[	"grief"	,	"깊은 고뇌, 슬픔"	],
[	"grieve"	,	"몹시 슬퍼하다, 마음 아파하다"	],
[	"grade"	,	"등급, 단계"	],
[	"gradual"	,	"단계적인, 점차적인"	],
[	"gradually"	,	"차츰, 서서히"	],
[	"graduate"	,	"졸업하다"	],
[	"undergraduate"	,	"대학생"	],
[	"ingredient"	,	"재료, 성분, 구성요소"	],
[	"great"	,	"거대한, 큰"	],
[	"congratulate"	,	"축하하다"	],
[	"grateful"	,	"고맙게 생각하는"	],
[	"gratify"	,	"만족시키다, 기쁘게 하다"	],
[	"gratitude"	,	"감사"	],
[	"agree"	,	"일치하다, 동의하다"	],
[	"agreement"	,	"약속, 협정, 일치"	],
[	"disagreement"	,	"불일치, 불화"	],
[	"degree"	,	"학위, 정도, 도"	],
[	"greed"	,	"끝없는 욕망, 탐욕"	],
[	"aggregate"	,	"총액, 합계, 종합하다"	],
[	"segregate"	,	"나누다, 분리시키다"	],
[	"congregate"	,	"모이다, 집합하다"	],
[	"congress"	,	"국회"	],
[	"progress"	,	"진보, 전진하다"	],
[	"progressive"	,	"진보적인, 혁신적인"	],
[	"aggressive"	,	"공격적인, 침략적인"	],
[	"grave"	,	"무덤, 엄숙한, 진지한"	],
[	"gravely"	,	"진지하게, 엄숙하게"	],
[	"gravel"	,	"자갈"	],
[	"engrave"	,	"새겨 넣다, 조각하다"	],
[	"aggravate"	,	"악화시키다, 화나게 하다"	],
[	"guide"	,	"길 안내를 하다"	],
[	"guideline"	,	"지침, 가이드라인"	],
[	"guidance"	,	"지도, 지휘"	],
[	"guard"	,	"경비요원, 보호하다"	],
[	"guarantee"	,	"보증, 보증하다"	],
[	"gut"	,	"창자, 내장, 용기"	],
[	"gutter"	,	"도랑, 시궁창, 배수로"	],
[	"gust"	,	"돌풍"	],
[	"disgust"	,	"메스꺼움, 혐오"	],
[	"gush"	,	"세차게 흘러나오다, 분출하다"	],
[	"gulp"	,	"꿀꺽꿀꺽 마시다"	],
[	"gull"	,	"갈매기"	],
[	"guess"	,	"추측하다, 짐작하다"	],
[	"vague"	,	"막연한, 애매한"	],
[	"vogue"	,	"유행, 인기, 유행하는"	],
[	"argue"	,	"논하다, 논의하다"	],
[	"argument"	,	"논의, 논쟁"	],
[	"gun"	,	"총"	],
[	"guest"	,	"손님"	],
[	"guitar"	,	"기타"	],
[	"have"	,	"가지고 있다"	],
[	"behavior"	,	"행동, 행위, 처신"	],
[	"misbehavior"	,	"내쁜 행동, 못된 짓"	],
[	"habit"	,	"버릇, 관습"	],
[	"habitual"	,	"습관적인, 평소의"	],
[	"inhabit"	,	"거주하다, 살다"	],
[	"inhabitant"	,	"거주자, 주민"	],
[	"habitat"	,	"서식지, 거주환경"	],
[	"exhibit"	,	"전시하다, 공개하다"	],
[	"inhibit"	,	"억제하다, 방해하다"	],
[	"prohibit"	,	"금지하다"	],
[	"hand"	,	"손"	],
[	"handle"	,	"손잡이, 핸들, 다루다"	],
[	"handful"	,	"한 움큼"	],
[	"handbook"	,	"안내서, 참고서"	],
[	"handbag"	,	"핸드백"	],
[	"handsome"	,	"미남의, 풍채가 좋은"	],
[	"prehend"	,	"잡다"	],
[	"apprehend"	,	"체포하다"	],
[	"comprehend"	,	"이해하다"	],
[	"comprehensible"	,	"알기 쉬운, 이해할 수 있는"	],
[	"comprehensive"	,	"포괄적인"	],
[	"harmony"	,	"조화, 화합, 일치"	],
[	"harmonica"	,	"하모니카"	],
[	"harp"	,	"하프"	],
[	"hard"	,	"단단한, 다루기 어려운, 힘든"	],
[	"hardly"	,	"거의 아니다"	],
[	"harsh"	,	"가혹한, 엄격한"	],
[	"harness"	,	"끄는 장비, 마구"	],
[	"harvest"	,	"수확, 추수"	],
[	"heir"	,	"상속인"	],
[	"inherit"	,	"상속받다, 물려받다"	],
[	"heritage"	,	"유산, 문화유산"	],
[	"heredity"	,	"유전"	],
[	"inherent"	,	"타고난, 고유의"	],
[	"shut"	,	"닫다, 뚜껑을 덮다"	],
[	"shop"	,	"가게, 상점"	],
[	"shoe"	,	"구두, 신"	],
]